export type Tool = {
  name: string;
  href: string;
  description: string;
  category: string;
};

export const ALL_TOOLS: Tool[] = [
  {
    name: "401(k) Match Calculator 2024",
    href: "/finance/401k-match-calculator",
    description: "Calculate your exact 401(k) employer match, annual savings, and projected retirement balance. Applies 2024 IRS $23,000 limit automatically. Free, no sign-up ...",
    category: "Finance",
  },
  {
    name: "Amazon FBA Calculator Canada",
    href: "/finance/amazon-fba-canada-calculator",
    description: "Calculate Amazon.ca referral fees, FBA fulfilment, storage, and net profit in CAD. Model Amazon Canada size tiers, tax impact, and inventory costs before you...",
    category: "Finance",
  },
  {
    name: "Amazon FBA Calculator UK",
    href: "/finance/amazon-fba-calculator-uk",
    description: "Calculate Amazon UK referral fees, FBA fulfilment, storage, VAT impact, and net profit per unit. Model your Amazon FBA margins before you source inventory.",
    category: "Finance",
  },
  {
    name: "Amortization Chart Calculator",
    href: "/finance/amortization-chart-calculator",
    description: "Free amortization chart calculator and amortization schedule maker. Generate detailed loan amortization tables, visualize payment breakdowns, and download yo...",
    category: "Finance",
  },
  {
    name: "Aspect Ratio Calculator",
    href: "/utility/aspect-ratio-calculator",
    description: "Free online aspect ratio calculator. Calculate 16:9, 4:3, 21:9, 1:1, 3:2 and custom aspect ratios instantly. Convert image and video dimensions with live pre...",
    category: "Utility",
  },
  {
    name: "Australia GST Calculator 2026",
    href: "/finance/australia-gst-calculator",
    description: "Free Australia GST calculator for 2026. Add or remove 10% GST from any amount. Calculate GST-inclusive and GST-exclusive prices instantly. Perfect for small ...",
    category: "Finance",
  },
  {
    name: "Australia Income Tax Calculator 2026\u201326",
    href: "/finance/income-tax-calculator-australia",
    description: "Free Australia income tax calculator for FY 2026\u201326. Includes Stage 3 tax cuts, Medicare levy, LITO offset, HECS-HELP repayment, and superannuation. Accurate...",
    category: "Finance",
  },
  {
    name: "Australia Stamp Duty Calculator 2026",
    href: "/finance/australia-stamp-duty-calculator",
    description: "Free Australia stamp duty calculator for NSW, VIC, QLD, WA, SA, TAS, ACT & NT. Calculate transfer duty with 2026 rates, first home buyer concessions, foreign...",
    category: "Finance",
  },
  {
    name: "BMR Calculator",
    href: "/health/bmr-calculator",
    description: "Calculate your Basal Metabolic Rate (BMR) using the Mifflin-St Jeor formula. Find out how many calories your body burns at rest and use it to set your calori...",
    category: "Health",
  },
  {
    name: "Bonus Tax Calculator",
    href: "/finance/bonus-tax-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Break Even Calculator",
    href: "/finance/break-even-calculator",
    description: "Calculate your break even point instantly. Free break even analysis tool with chart maker, profit forecasting, and CSV export. No sign-up required.",
    category: "Finance",
  },
  {
    name: "Business Risk Exposure Score Calculator",
    href: "/finance/business-risk-exposure-score-calculator",
    description: "Free business risk exposure score calculator. Assess operational, financial, cyber, legal, market, physical, and reputational risk across 35+ data points. Ge...",
    category: "Finance",
  },
  {
    name: "CD Ladder Calculator",
    href: "/finance/cd-ladder-calculator",
    description: "Free CD ladder calculator: plan multi-rung certificate of deposit ladders, use our cd maturity calculator to track maturity dates, and our monthly cd interes...",
    category: "Finance",
  },
  {
    name: "California Sales Tax Calculator 2026",
    href: "/finance/sales-tax-california-calculator",
    description: "Free California sales tax calculator for 2026. Look up sales tax rates for any CA city or county \u2014 from Los Angeles (10.25%) to San Francisco (8.625%) to San...",
    category: "Finance",
  },
  {
    name: "Calorie Calculator (TDEE)",
    href: "/health/calorie-calculator",
    description: "Calculate your Total Daily Energy Expenditure (TDEE) and daily calorie needs based on your age, weight, height, and activity level using the Mifflin-St Jeor ...",
    category: "Health",
  },
  {
    name: "Canada HST/GST Calculator",
    href: "/finance/canada-hst-gst-calculator",
    description: "Free Canada HST GST PST QST calculator for all provinces and territories. Add tax or reverse calculate. Accurate 2026 rates for Ontario, BC, Quebec, Alberta ...",
    category: "Finance",
  },
  {
    name: "Canada Sales Tax Calculator 2026",
    href: "/finance/sales-tax-canada-calculator",
    description: "Free Canada sales tax calculator for 2026. Calculate GST, HST, and PST for all 13 provinces and territories \u2014 Ontario (13% HST), Quebec (14.975% GST+QST), BC...",
    category: "Finance",
  },
  {
    name: "Canadian Mortgage Qualifier Calculator 2026",
    href: "/real-estate/mortgage-qualifier-canada",
    description: "Find out exactly how much mortgage you qualify for in Canada. Includes 2026 mortgage stress test (contract rate +2%, min 5.25%), CMHC insurance premiums, GDS...",
    category: "Real Estate",
  },
  {
    name: "Cap Rate Calculator 2026",
    href: "/real-estate/cap-rate-calculator",
    description: "Free cap rate calculator for real estate investors. Calculate Net Operating Income (NOI), capitalization rate, and cash-on-cash return. Includes 2026 market ...",
    category: "Real Estate",
  },
  {
    name: "Car Depreciation Calculator by Model 2026",
    href: "/finance/car-depreciation-calculator",
    description: "Free car depreciation calculator by make and model. Calculate accurate resale value, depreciation curves, and total cost of ownership for 500+ vehicles. Comp...",
    category: "Finance",
  },
  {
    name: "Case Converter for Writing, SEO, and Developer Formats",
    href: "/text/case-converter",
    description: "Convert text into uppercase, lowercase, smart title case, sentence case, camelCase, PascalCase, kebab-case, snake_case, CONSTANT_CASE, and more.",
    category: "Text",
  },
  {
    name: "Cash on Cash Return Calculator",
    href: "/real-estate/cash-on-cash-return-calculator",
    description: "Free cash on cash return calculator for real estate investors. Calculate CoC return, cap rate, NOI, DSCR, GRM, and break-even ratio. Includes full income sta...",
    category: "Real Estate",
  },
  {
    name: "Compound Interest Calculator with Monthly Contributions",
    href: "/finance/compound-interest-calculator",
    description: "Free compound interest calculator with monthly contributions. See how regular deposits grow over time with daily, monthly, or annual compounding. Includes in...",
    category: "Finance",
  },
  {
    name: "Concrete Volume Calculator",
    href: "/construction/concrete-volume-calculator",
    description: "Calculate concrete volume for slabs, footings, columns, holes, and stairs. Estimate cubic yards, bag counts, waste factor, and project cost before you pour.",
    category: "Construction",
  },
  {
    name: "Confirm Your Start Date",
    href: "/finance/cpp-ei-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Convert Image to Base64",
    href: "/image/convert-image-to-base64",
    description: "Convert any image into a Base64 string or data URL directly in your browser. Copy the output for use in CSS, HTML, or JSON.",
    category: "Image",
  },
  {
    name: "Crypto Mining Calculator 2026",
    href: "/finance/crypto-mining-calculator",
    description: "Free crypto mining calculator for Bitcoin, Ethereum, and altcoins. Calculate GPU mining profitability, ASIC mining ROI, electricity costs, and daily/monthly ...",
    category: "Finance",
  },
  {
    name: "Dropshipping Break Even",
    href: "/finance/dropshipping-break-even",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Duplicate Word Finder",
    href: "/text/duplicate-word-finder",
    description: "Find repeated words in text instantly with a free duplicate word finder. Surface overused terms, duplicate counts, and the most repeated words in one tool.",
    category: "Text",
  },
  {
    name: "EMI Calculator",
    href: "/finance/emi-calculator",
    description: "Use this free EMI calculator to estimate monthly loan payments, total interest, total repayment, affordability, and maximum loan size for home, car, and pers...",
    category: "Finance",
  },
  {
    name: "Equity Dilution Calculator 2026",
    href: "/finance/equity-dilution-calculator",
    description: "Free equity dilution calculator for startup founders. Calculate ownership percentage after seed, Series A/B/C funding, option pool expansion, convertible not...",
    category: "Finance",
  },
  {
    name: "Etsy Profit Calculator 2026",
    href: "/finance/etsy-profit-calculator",
    description: "Calculate your true Etsy profit instantly. Accurate 2024/2026 Etsy fee calculator covering US, UK, Canada, and Australia \u2014 transaction fees, listing fees, of...",
    category: "Finance",
  },
  {
    name: "First-Time Buyers Evaluating Down Payments",
    href: "/finance/pmi-calculator",
    description: "Free PMI insurance calculator using 2026 rate tables. Calculate your monthly private mortgage insurance cost, see when PMI drops off, and find out how much y...",
    category: "Finance",
  },
  {
    name: "Free AI Humanizer \u2013 Rewrite ChatGPT, Claude & Gemini Text to Sound Human",
    href: "/ai/ai-humanizer",
    description: "Convert AI-generated text to human-like writing. Remove AI detection patterns while preserving meaning. Bypass GPTZero & Turnitin. No signup required.",
    category: "Ai",
  },
  {
    name: "Free Barcode Generator \u2013 Create UPC, EAN-13 & CODE128 Barcodes Online",
    href: "/utility/barcode-generator",
    description: "Generate free barcodes online instantly. Supports CODE128, UPC, EAN-13, EAN-8, ITF-14 and more. Customize colors and size, then download as a high-resolution...",
    category: "Utility",
  },
  {
    name: "Free Barcode Scanner Online \u2013 Scan UPC & EAN Codes (No App Needed)",
    href: "/utility/barcode-scanner",
    description: "Scan barcodes online free using your camera or by uploading a photo. Reads UPC, EAN-13, EAN-8, CODE-128 and more. Works on iPhone, Android, and laptop \u2014 no a...",
    category: "Utility",
  },
  {
    name: "Free CV Resume Builder",
    href: "/utility/free-cv-resume-builder",
    description: "Build a professional resume online for free with editable sections, multiple templates, local autosave, and print-to-PDF export.",
    category: "Utility",
  },
  {
    name: "Free DNS Lookup Tool",
    href: "/utility/dns-checker",
    description: "Free DNS checker tool \u2014 instantly look up A, MX, CNAME, TXT, NS and more records for any domain. Results are fetched server-side with no sign-up required.",
    category: "Utility",
  },
  {
    name: "Free Invoice Generator with VAT, GST & HST",
    href: "/finance/invoice-generator",
    description: "Free online invoice generator with automatic VAT, GST and HST calculation. Create professional invoices for UK, Australia, Canada, USA and more. Download as ...",
    category: "Finance",
  },
  {
    name: "Create QR Code Online - Static, No Expiry, Instant Download",
    href: "/utility/create-qr-code-online",
    description: "Create static QR codes for URLs, Wi-Fi, WhatsApp, business cards, and more. No expiry, no scan limits, instant PNG download, and no sign-up required.",
    category: "Utility",
  },
  {
    name: "Free QR Code Scanner Online \u2013 Scan from Camera or Image (No App Needed)",
    href: "/utility/qr-code-scanner",
    description: "Scan QR codes online for free using your camera or by uploading an image. Works on iPhone, Android, and desktop. No app, no sign-up, 100% private.",
    category: "Utility",
  },
  {
    name: "Free Social Media Carousel Builder",
    href: "/design/free-social-media-carousel-builder",
    description: "Create professional social media carousels in seconds for Instagram, LinkedIn, and TikTok. High-conversion templates, continuous backgrounds, and easy PDF/PN...",
    category: "Design",
  },
  {
    name: "Free Word Cloud Generator - Create a Word Cloud from Any Text",
    href: "/text/word-cloud-generator",
    description: "Paste any text and instantly generate a frequency-based word cloud. Filter common words, control word count, and copy or download the top terms output.",
    category: "Text",
  },
  {
    name: "Fuel Cost Calculator 2026",
    href: "/utility/fuel-cost-calculator",
    description: "Free fuel cost calculator for road trips and daily commuting. Calculate gas costs by mileage, MPG, and fuel price. Compare vehicle fuel efficiency, estimate ...",
    category: "Utility",
  },
  {
    name: "GPA Calculator",
    href: "/utility/gpa-calculator",
    description: "Free GPA calculator for high school and college. Calculate my GPA unweighted or weighted (AP/IB/Honors), convert grades to GPA, percentage to GPA, and find y...",
    category: "Utility",
  },
  {
    name: "Gas Mileage Calculator",
    href: "/utility/gas-mileage-calculator",
    description: "Free gas mileage calculator to calculate MPG, trip fuel costs, and annual gas savings. High-tech HUD diagnostic interface for vehicle efficiency tracking and...",
    category: "Utility",
  },
  {
    name: "General Liability Insurance Cost Estimator 2026",
    href: "/finance/general-liability-insurance-cost-estimator",
    description: "Free general liability insurance cost estimator for small businesses. Calculate premiums by industry, revenue, location, employees, and coverage limits. Get ...",
    category: "Finance",
  },
  {
    name: "Halal Mortgage Calculator",
    href: "/finance/halal-mortgage-calculator",
    description: "Compare Halal home finance structures: Diminishing Musharakah, Murabaha, and Ijara. Instant monthly payments and full schedules for Sharia-compliant home buy...",
    category: "Finance",
  },
  {
    name: "Hong Kong Stamp Duty Calculator",
    href: "/real-estate/hong-kong-stamp-duty-calculator",
    description: "Estimate Hong Kong residential stamp duty using the current Scale 2 schedule. Compare price bands and budget the ad valorem duty before completion.",
    category: "Real Estate",
  },
  {
    name: "House Affordability Calculator Australia",
    href: "/finance/house-affordability-calculator-australia",
    description: "Free house affordability calculator for Australia. Calculate stamp duty by state, LMI, FHOG, monthly repayments and borrowing capacity with the APRA 3% servi...",
    category: "Finance",
  },
  {
    name: "House Affordability Calculator Canada (2026)",
    href: "/real-estate/house-affordability-calculator-canada",
    description: "Calculate how much home you can afford in Canada. Includes 2026 mortgage stress test, CMHC insurance, and land transfer tax for all provinces.",
    category: "Real Estate",
  },
  {
    name: "Hreflang Generator",
    href: "/seo/hreflang-generator",
    description: "No description available.",
    category: "Seo",
  },
  {
    name: "Image to Text OCR Converter",
    href: "/text/convert-image-to-text",
    description: "Extract text from images with a free OCR converter. Convert JPG, PNG, WEBP, and BMP images into editable text, clean the output, and copy or download it.",
    category: "Text",
  },
  {
    name: "Income Tax Calculator Ireland 2026",
    href: "/finance/income-tax-calculator-ireland",
    description: "Free Ireland income tax calculator for 2026/2026. Calculate your exact take-home pay after PAYE, Universal Social Charge (USC) and PRSI. Accurate for employe...",
    category: "Finance",
  },
  {
    name: "India Income Tax Calculator 2026\u201326",
    href: "/finance/income-tax-calculator-india",
    description: "Free India income tax calculator FY 2026\u201326. Compare Old vs New Tax Regime side by side. Includes Section 80C, 80D, HRA, NPS deductions, surcharge, 4% cess a...",
    category: "Finance",
  },
  {
    name: "Inheritance Tax Calculator 2026",
    href: "/finance/inheritance-tax-calculator",
    description: "Free inheritance tax calculator for UK, USA, Ireland, France, Germany, Spain, Italy, Canada, Australia & India. Calculate estate tax, succession duty, and ca...",
    category: "Finance",
  },
  {
    name: "Keyword Clustering",
    href: "/seo/keyword-clustering",
    description: "No description available.",
    category: "Seo",
  },
  {
    name: "Marketing ROI Calculator",
    href: "/marketing/marketing-roi-calculator",
    description: "Calculate your marketing ROI instantly. Analyze ROAS, ROMI, CAC, and LTV with our professional-grade calculator. Includes 1,500+ word guide on growth unit ec...",
    category: "Marketing",
  },
  {
    name: "Meta Description Checker",
    href: "/seo/meta-description-checker",
    description: "No description available.",
    category: "Seo",
  },
  {
    name: "Morse Code Translator",
    href: "/text/binary-code-translator",
    description: "Translate text to Morse code and Morse code back to text with support for letters, numbers, and punctuation.",
    category: "Text",
  },
  {
    name: "Morse Code Translator - Text to Morse Code, Morse to Text, and Audio",
    href: "/text/morse-code-translator",
    description: "Translate text to Morse code, decode Morse to text, play Morse audio, and use a full alphabet chart with letters, numbers, punctuation, and SOS examples.",
    category: "Text",
  },
  {
    name: "NYC Transfer Tax Calculator 2026",
    href: "/real-estate/nyc-transfer-tax-calculator",
    description: "Calculate NYC Real Property Transfer Tax (RPTT), NYS transfer tax, and mansion tax instantly. Updated 2026 rates for condos, co-ops, and 1-3 family homes.",
    category: "Real Estate",
  },
  {
    name: "Net Salary Calculator 2026",
    href: "/finance/net-salary-calculator",
    description: "Free gross to net salary calculator and net to gross income calculator for 2026. Calculate net pay from gross income with federal, state, FICA taxes. Accurat...",
    category: "Finance",
  },
  {
    name: "Paint Coverage Calculator",
    href: "/construction/paint-coverage-calculator",
    description: "Calculate how much paint you need for rooms, walls, ceilings, and primer coats. Estimate gallons, liters, and project coverage before you buy paint.",
    category: "Construction",
  },
  {
    name: "Password Strength Checker",
    href: "/utility/password-strength-checker",
    description: "No description available.",
    category: "Utility",
  },
  {
    name: "Precision Flooring Material Calculator",
    href: "/construction/flooring-material-calculator",
    description: "Free flooring calculator for hardwood, LVP, laminate, and tile. Calculate exact box counts, adjusted waste margins, and project costs across multiple rooms.",
    category: "Construction",
  },
  {
    name: "Price per Square Foot Calculator",
    href: "/real-estate/price-per-square-foot-calculator",
    description: "Calculate price per square foot or square metre, reverse-calculate total property value, compare properties, and check rent or sale rates on the same size-ad...",
    category: "Real Estate",
  },
  {
    name: "Product Pricing Calculator",
    href: "/finance/product-pricing-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "RRSP Contributions",
    href: "/finance/canada-income-tax-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Readability / Flesch-Kincaid Calculator",
    href: "/text/readability-flesch-kincaid-calculator",
    description: "Score pasted text for reading ease, grade level, and sentence complexity.",
    category: "Text",
  },
  {
    name: "Rent vs Buy Calculator",
    href: "/real-estate/rent-vs-buy-calculator",
    description: "Should you rent or buy a house? Our rent vs buy calculator factors in mortgage interest tax savings, property appreciation, opportunity cost, and the SALT de...",
    category: "Real Estate",
  },
  {
    name: "Rental Yield Calculator",
    href: "/real-estate/rental-yield-calculator",
    description: "Free rental yield calculator for property investors in the UK, US, and Australia. Calculate gross yield, net yield, cash-on-cash return, and cap rate. Compar...",
    category: "Real Estate",
  },
  {
    name: "Resize Photo for Instagram 2026",
    href: "/image/resize-photo-instagram-online",
    description: "Instantly resize any image for Instagram Square, Portrait, Story and Profile formats. Prevent compression, avoid cropping and maintain full quality. 100% Free.",
    category: "Image",
  },
  {
    name: "Roofing Material Calculator",
    href: "/construction/roofing-material-calculator",
    description: "Free professional roofing calculator. Estimate squares, bundles, and accessory materials like ridge caps and underlayment with pitch adjustment and waste fac...",
    category: "Construction",
  },
  {
    name: "Rule of 72 Calculator",
    href: "/finance/rule-of-72-calculator",
    description: "Free Rule of 72 calculator with steps, monthly compounding mode, and contribution support. Understand the rule of 72 formula in finance, see how fast your mo...",
    category: "Finance",
  },
  {
    name: "SIP Calculator India 2026",
    href: "/finance/india-sip-calculator",
    description: "Free India SIP calculator with step-up SIP, lumpsum and SWP modes. Calculate mutual fund returns, wealth gained, and maturity value with inflation adjustment...",
    category: "Finance",
  },
  {
    name: "Salary After Tax Calculator",
    href: "/finance/salary-after-tax-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Saudi End of Service Calculator",
    href: "/finance/saudi-end-of-service-calculator",
    description: "Free Saudi Arabia end of service benefit calculator. Accurate EOSB calculation per Saudi Labor Law Articles 84\u201388. Covers resignation, termination, and contr...",
    category: "Finance",
  },
  {
    name: "Scotland LBTT Calculator",
    href: "/real-estate/scotland-lbtt-calculator",
    description: "Calculate Scotland LBTT with current residential bands, first-time buyer relief, and Additional Dwelling Supplement. Budget Scottish property tax before comp...",
    category: "Real Estate",
  },
  {
    name: "Singapore Buyer's Stamp Duty Calculator",
    href: "/real-estate/singapore-buyers-stamp-duty-calculator",
    description: "Calculate Singapore BSD and ABSD for residential property purchases. Compare buyer profiles, estimate total stamp duty, and budget your upfront costs.",
    category: "Real Estate",
  },
  {
    name: "Singapore Property Stamp Duty Calculator",
    href: "/real-estate/singapore-property-stamp-duty-calculator",
    description: "Calculate Singapore residential BSD, ABSD, and SSD using current buyer profiles and recent seller-duty regimes.",
    category: "Real Estate",
  },
  {
    name: "Singapore Seller's Stamp Duty Calculator",
    href: "/real-estate/singapore-sellers-stamp-duty-calculator",
    description: "Estimate Singapore residential Seller's Stamp Duty using the acquisition date, disposal date, and current SSD regime.",
    category: "Real Estate",
  },
  {
    name: "Social Media Character Counter",
    href: "/utility/social-media-character-counter",
    description: "No description available.",
    category: "Utility",
  },
  {
    name: "Social Media Image Resizer",
    href: "/utility/social-media-image-resizer",
    description: "No description available.",
    category: "Utility",
  },
  {
    name: "Stocks & Investments",
    href: "/finance/capital-gains-tax-canada-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Sydney Stamp Duty Calculator",
    href: "/real-estate/stamp-duty-calculator-nsw",
    description: "Calculate NSW stamp duty (transfer duty) for Sydney property purchases. Includes 2026 rates, first home buyer exemptions ($800k), foreign buyer surcharge (8%...",
    category: "Real Estate",
  },
  {
    name: "TDS Calculator India 2026-26",
    href: "/finance/india-tds-calculator",
    description: "Free India TDS calculator for FY 2026-26 (AY 2026-27). Calculate TDS on salary, rent, professional fees, contractor payments, interest & commission. Includes...",
    category: "Finance",
  },
  {
    name: "Tip Calculator",
    href: "/finance/tip-calculator",
    description: "Free tip calculator for restaurants, bars, hotels and more. Calculate tip by percentage, split the bill between any number of people, use our tip converter t...",
    category: "Finance",
  },
  {
    name: "Toronto Land Transfer Tax Calculator",
    href: "/real-estate/land-transfer-tax-calculator-toronto",
    description: "Calculate Ontario land transfer tax and Toronto municipal land transfer tax with first-time buyer rebates and NRST scenarios for 2026 budgeting.",
    category: "Real Estate",
  },
  {
    name: "UK Stamp Duty Calculator",
    href: "/real-estate/uk-stamp-duty-calculator",
    description: "Calculate current residential SDLT for England and Northern Ireland, including second home surcharge, buy-to-let rates, and first-time buyer relief.",
    category: "Real Estate",
  },
  {
    name: "UK Student Loan Repayment Calculator",
    href: "/finance/uk-student-loan-repayment-calculator",
    description: "Free UK student loan repayment calculator for Plans 1, 2, 4 and 5. See your monthly repayments, total repaid, interest charged, and whether your loan gets wr...",
    category: "Finance",
  },
  {
    name: "US Navy Body Fat Calculator 2026",
    href: "/health/us-navy-body-fat-calculator",
    description: "Official US Navy body fat calculator using OPNAVINST 6110.1J tape measurement standards. Calculate Navy PRT body fat percentage for males and females. Accura...",
    category: "Health",
  },
  {
    name: "US Self-Employment Tax Calculator 2026",
    href: "/finance/us-self-employment-tax-calculator",
    description: "Free US self-employment tax calculator for 2026. Calculate Social Security and Medicare taxes for freelancers, contractors, and sole proprietors. Includes de...",
    category: "Finance",
  },
  {
    name: "Us Take Home Pay Calculator",
    href: "/finance/us-take-home-pay-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Utm Builder",
    href: "/utility/utm-builder",
    description: "Start with the basics if you need a clean explanation of source, medium, campaign, term, and content.",
    category: "Utility",
  },
  {
    name: "Wales LTT Calculator",
    href: "/real-estate/wales-ltt-calculator",
    description: "Calculate Wales Land Transaction Tax with current residential bands and higher rates. Estimate your Welsh property tax before exchange and completion.",
    category: "Real Estate",
  },
  {
    name: "What Is My Ip",
    href: "/utility/what-is-my-ip",
    description: "Look up A, MX, TXT, and NS records for any domain or IP.",
    category: "Utility",
  },
  {
    name: "Word Frequency Counter",
    href: "/text/word-frequency",
    description: "Analyze word frequency, keyword density, repeated words, dominant topics, rare words, and vocabulary diversity with a free text analysis tool.",
    category: "Text",
  },
  {
    name: "Workers Comp Premium Calculator by Industry 2026",
    href: "/finance/workers-comp-premium-calculator",
    description: "Free workers compensation insurance premium calculator by industry and state. Estimate costs using class codes, payroll, experience mods, and state rates. Up...",
    category: "Finance",
  },
  {
    name: "Young Investors with Long Horizons",
    href: "/finance/dividend-reinvestment-calculator",
    description: "No description available.",
    category: "Finance",
  },
  {
    name: "Youtube Title Checker",
    href: "/seo/youtube-title-checker",
    description: "No description available.",
    category: "Seo",
  },
  {
    name: "Zakat Calculator 2024",
    href: "/finance/zakat-calculator",
    description: "Free online zakat calculator. Calculate zakat on gold, silver, savings, salary, business inventory and investments. Up-to-date nisab threshold. Trusted by Mu...",
    category: "Finance",
  },
  {
    name: "free image background remover online",
    href: "/image/free-image-background-remover-online",
    description: "Perfect free Canva background removal alternative\u2014remove image backgrounds instantly in your browser with no upload and no sign-up. Supports PNG, JPG & WEBP.",
    category: "Image",
  },
  {
    name: "xG Calculator",
    href: "/utility/xg-expected-goals-calculator",
    description: "Calculate the expected goals (xG) value of any football shot. Interactive pitch tool \u2014 adjust distance, angle, shot type, pressure and assist type. Free, ins...",
    category: "Utility",
  },
];
