export interface VisaType {
  id: string;
  name: string;
  category: 'tourist' | 'employment' | 'golden' | 'green' | 'transit' | 'family' | 'student';
  duration: string;
  entryType: 'single' | 'multiple' | 'na';
  baseFeeAED: number;
  baseFeeUSD: number;
  processingDays: string;
  requirements: string[];
  description: string;
  hiddenCosts: { name: string; costAED: number; optional: boolean }[];
}

export const visaTypes: VisaType[] = [
  {
    id: 'tourist-30-single',
    name: '30-Day Tourist Visa (Single Entry)',
    category: 'tourist',
    duration: '30 days',
    entryType: 'single',
    baseFeeAED: 350,
    baseFeeUSD: 95,
    processingDays: '1-3 working days',
    requirements: ['Passport valid 6+ months', 'Passport photo', 'Travel insurance'],
    description: 'The most popular short-stay visa for leisure and business visitors to Dubai and Abu Dhabi.',
    hiddenCosts: [
      { name: 'Express processing', costAED: 150, optional: true },
      { name: 'Travel insurance (mandatory)', costAED: 120, optional: false },
    ],
  },
  {
    id: 'tourist-30-multiple',
    name: '30-Day Tourist Visa (Multiple Entry)',
    category: 'tourist',
    duration: '30 days per visit',
    entryType: 'multiple',
    baseFeeAED: 690,
    baseFeeUSD: 188,
    processingDays: '1-3 working days',
    requirements: ['Passport valid 6+ months', 'Passport photo', 'Proof of funds'],
    description: 'Ideal for business travelers making multiple trips to the UAE within the validity period.',
    hiddenCosts: [
      { name: 'Express processing', costAED: 200, optional: true },
      { name: 'Travel insurance', costAED: 150, optional: false },
    ],
  },
  {
    id: 'tourist-60-single',
    name: '60-Day Tourist Visa (Single Entry)',
    category: 'tourist',
    duration: '60 days',
    entryType: 'single',
    baseFeeAED: 500,
    baseFeeUSD: 136,
    processingDays: '1-3 working days',
    requirements: ['Passport valid 6+ months', 'Passport photo', 'Bank statements (last 3 months)'],
    description: 'Extended stay option for travelers visiting family or exploring long-term tourism in the UAE.',
    hiddenCosts: [
      { name: 'Express processing', costAED: 200, optional: true },
      { name: 'Travel insurance', costAED: 200, optional: false },
    ],
  },
  {
    id: 'tourist-90-single',
    name: '90-Day Tourist Visa (Single Entry)',
    category: 'tourist',
    duration: '90 days',
    entryType: 'single',
    baseFeeAED: 600,
    baseFeeUSD: 163,
    processingDays: '2-5 working days',
    requirements: ['Passport valid 6+ months', 'Passport photo', 'Bank statements (last 6 months)', 'Travel insurance'],
    description: 'Long-stay tourist visa for extended family visits or deep exploration of the Emirates.',
    hiddenCosts: [
      { name: 'Express processing', costAED: 250, optional: true },
      { name: 'Travel insurance', costAED: 300, optional: false },
    ],
  },
  {
    id: 'tourist-5year',
    name: '5-Year Multiple Entry Tourist Visa',
    category: 'tourist',
    duration: '5 years (90 days per visit)',
    entryType: 'multiple',
    baseFeeAED: 1400,
    baseFeeUSD: 381,
    processingDays: '5-7 working days',
    requirements: ['Passport valid 6+ months', 'Passport photo', 'Bank balance USD 4,000+ (last 6 months)', 'Health insurance'],
    description: 'The smartest choice for frequent travelers. Unlimited entries over 5 years with 90 days per visit, extendable to 180 days annually.',
    hiddenCosts: [
      { name: 'Express processing', costAED: 300, optional: true },
      { name: 'Health insurance (annual)', costAED: 800, optional: false },
    ],
  },
  {
    id: 'transit-48',
    name: '48-Hour Transit Visa',
    category: 'transit',
    duration: '48 hours',
    entryType: 'single',
    baseFeeAED: 257,
    baseFeeUSD: 70,
    processingDays: '1-2 working days',
    requirements: ['Confirmed onward ticket', 'Passport valid 3+ months'],
    description: 'Free for some nationalities; paid for others. Perfect for short layovers in Dubai or Abu Dhabi.',
    hiddenCosts: [
      { name: 'Airport service fee', costAED: 50, optional: false },
    ],
  },
  {
    id: 'transit-96',
    name: '96-Hour Transit Visa',
    category: 'transit',
    duration: '96 hours (4 days)',
    entryType: 'single',
    baseFeeAED: 477,
    baseFeeUSD: 130,
    processingDays: '1-2 working days',
    requirements: ['Confirmed onward ticket', 'Passport valid 3+ months', 'Hotel booking'],
    description: 'Four-day transit visa for travelers wanting a quick taste of the UAE between flights.',
    hiddenCosts: [
      { name: 'Airport service fee', costAED: 50, optional: false },
    ],
  },
  {
    id: 'employment-2year',
    name: '2-Year Employment Visa',
    category: 'employment',
    duration: '2 years',
    entryType: 'na',
    baseFeeAED: 4500,
    baseFeeUSD: 1225,
    processingDays: '5-12 working days',
    requirements: ['Valid job offer from UAE company', 'Degree attestation', 'Medical fitness test', 'Emirates ID'],
    description: 'Standard work residence visa sponsored by mainland or free zone employers. Most common visa for expats in Dubai.',
    hiddenCosts: [
      { name: 'Medical fitness test', costAED: 500, optional: false },
      { name: 'Emirates ID (2 years)', costAED: 370, optional: false },
      { name: 'Visa stamping', costAED: 500, optional: false },
      { name: 'Health insurance (annual)', costAED: 1500, optional: false },
      { name: 'Degree attestation', costAED: 800, optional: false },
    ],
  },
  {
    id: 'employment-green',
    name: 'Green Visa (5-Year)',
    category: 'green',
    duration: '5 years',
    entryType: 'na',
    baseFeeAED: 4000,
    baseFeeUSD: 1089,
    processingDays: '7-14 working days',
    requirements: ['Skilled professional (bachelor\'s degree min)', 'Valid employment contract', 'Salary AED 15,000+/month', 'Medical fitness test'],
    description: 'Self-sponsored 5-year residency for skilled employees, freelancers, and investors. No employer sponsor needed.',
    hiddenCosts: [
      { name: 'Medical fitness test', costAED: 500, optional: false },
      { name: 'Emirates ID (5 years)', costAED: 570, optional: false },
      { name: 'Health insurance (annual)', costAED: 2000, optional: false },
    ],
  },
  {
    id: 'golden-10year',
    name: 'Golden Visa (10-Year)',
    category: 'golden',
    duration: '10 years',
    entryType: 'na',
    baseFeeAED: 3800,
    baseFeeUSD: 1035,
    processingDays: '2-4 weeks',
    requirements: ['Investment AED 2M+ in property OR public investment', 'OR Salary AED 30,000+/month (professionals)', 'Medical fitness test', 'Health insurance'],
    description: 'Long-term residency for investors, entrepreneurs, scientists, and exceptional talents. Self-sponsored with family sponsorship rights.',
    hiddenCosts: [
      { name: 'Medical fitness test', costAED: 700, optional: false },
      { name: 'Emirates ID (10 years)', costAED: 1070, optional: false },
      { name: 'Health insurance (annual)', costAED: 3000, optional: false },
      { name: 'Document attestation', costAED: 500, optional: false },
      { name: 'PRO service (optional)', costAED: 2000, optional: true },
    ],
  },
  {
    id: 'golden-5year',
    name: 'Golden Visa (5-Year)',
    category: 'golden',
    duration: '5 years',
    entryType: 'na',
    baseFeeAED: 3300,
    baseFeeUSD: 899,
    processingDays: '2-4 weeks',
    requirements: ['Property investment AED 2M+', 'OR Entrepreneur with AED 1M+ revenue', 'Medical fitness test'],
    description: '5-year Golden Visa option primarily for real estate investors and select entrepreneurs.',
    hiddenCosts: [
      { name: 'Medical fitness test', costAED: 700, optional: false },
      { name: 'Emirates ID (5 years)', costAED: 570, optional: false },
      { name: 'Health insurance (annual)', costAED: 2500, optional: false },
    ],
  },
  {
    id: 'family-2year',
    name: 'Family Residence Visa (2-Year)',
    category: 'family',
    duration: '2 years',
    entryType: 'na',
    baseFeeAED: 2200,
    baseFeeUSD: 599,
    processingDays: '5-10 working days',
    requirements: ['Sponsor salary AED 4,000+/month (or AED 3,000 + accommodation)', 'Marriage certificate (attested)', 'Birth certificates for children', 'Medical fitness test (18+)'],
    description: 'Sponsored by a parent or spouse holding a valid UAE residence visa. Covers spouse, children, and parents.',
    hiddenCosts: [
      { name: 'Medical fitness test (18+)', costAED: 500, optional: false },
      { name: 'Emirates ID', costAED: 370, optional: false },
      { name: 'Health insurance (annual)', costAED: 1200, optional: false },
      { name: 'Document attestation', costAED: 400, optional: false },
    ],
  },
  {
    id: 'student',
    name: 'Student Visa',
    category: 'student',
    duration: '1 year (renewable)',
    entryType: 'na',
    baseFeeAED: 2500,
    baseFeeUSD: 681,
    processingDays: '5-10 working days',
    requirements: ['University acceptance letter', 'Passport valid 6+ months', 'Medical fitness test', 'Emirates ID'],
    description: 'For international students enrolled in UAE universities or schools. Renewable annually based on enrollment.',
    hiddenCosts: [
      { name: 'Medical fitness test', costAED: 500, optional: false },
      { name: 'Emirates ID', costAED: 270, optional: false },
      { name: 'Health insurance (annual)', costAED: 1000, optional: false },
    ],
  },
];

export const categories = [
  { id: 'all', label: 'All Visa Types' },
  { id: 'tourist', label: 'Tourist & Visit' },
  { id: 'employment', label: 'Employment & Work' },
  { id: 'golden', label: 'Golden Visa' },
  { id: 'green', label: 'Green Visa' },
  { id: 'family', label: 'Family Sponsorship' },
  { id: 'transit', label: 'Transit' },
  { id: 'student', label: 'Student' },
];

export const exchangeRate = 3.67; // 1 USD = 3.67 AED
