import type { Metadata } from "next";
import Link from "next/link";
import CashOnCashCalculator from "@/components/CashOnCashCalculator";
import { Info } from "lucide-react";

export const metadata: Metadata = {
  title: "Cash on Cash Return Calculator — Real Estate Investment Analysis",
  description:
    "Free cash on cash return calculator for real estate investors. Calculate CoC return, cap rate, NOI, DSCR, GRM, and break-even ratio. Includes full income statement, expense breakdown, and multi-year projection.",
  keywords: [
    "cash on cash return calculator",
    "cash on cash return real estate",
    "how to calculate cash on cash return",
    "rental property cash on cash return",
    "what is a good cash on cash return",
    "cap rate calculator",
    "noi calculator real estate",
    "rental property return calculator",
    "real estate investment calculator",
    "dscr calculator rental property",
    "gross rent multiplier calculator",
    "rental property cash flow calculator",
  ],
  openGraph: {
    title: "Cash on Cash Return Calculator — Real Estate Investment",
    description:
      "Calculate cash on cash return, cap rate, NOI, DSCR, and 10-year projections for any rental property. Free, comprehensive real estate investment analysis.",
    url: "https://findbest.tools/real-estate/cash-on-cash-return-calculator",
  },
  alternates: {
    canonical: "https://findbest.tools/real-estate/cash-on-cash-return-calculator",
  },
};

const schema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Cash on Cash Return Calculator",
  applicationCategory: "FinanceApplication",
  operatingSystem: "Web",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  description:
    "Free cash on cash return calculator for rental property investors. Calculates CoC return, cap rate, NOI, DSCR, GRM, and multi-year projections.",
};

// ─── Content data ──────────────────────────────────────────────────

const METRICS_TABLE = [
  {
    metric: "Cash on Cash Return (CoC)",
    formula: "Annual Cash Flow ÷ Total Cash Invested",
    good: "8–12%+",
    what: "How much your actual cash investment earns in cash per year. The most important metric for leveraged investors.",
  },
  {
    metric: "Cap Rate",
    formula: "NOI ÷ Property Value",
    good: "5–10%+",
    what: "Property performance independent of financing. Useful for comparing properties regardless of how they're financed.",
  },
  {
    metric: "Net Operating Income (NOI)",
    formula: "EGI − Operating Expenses",
    good: "Positive",
    what: "Revenue after vacancy and operating expenses but before debt service. The foundation of all commercial valuation.",
  },
  {
    metric: "DSCR",
    formula: "NOI ÷ Annual Debt Service",
    good: "≥ 1.25",
    what: "Debt Service Coverage Ratio. Lenders require ≥ 1.20–1.25. Below 1.0 means the property doesn't cover its own mortgage.",
  },
  {
    metric: "Gross Rent Multiplier (GRM)",
    formula: "Purchase Price ÷ Annual Gross Rent",
    good: "< 10",
    what: "Quick comparison tool. A GRM of 10 means the property costs 10 years of gross rent. Lower is generally better.",
  },
  {
    metric: "Break-Even Ratio (BER)",
    formula: "(Expenses + Debt Service) ÷ Gross Income",
    good: "< 85%",
    what: "The occupancy level needed to cover all costs. Most lenders want BER ≤ 85%.",
  },
];

const FAQS = [
  {
    q: "What is cash on cash return in real estate?",
    a: "Cash on cash return (CoC) is a real estate investment metric that measures the annual pre-tax cash flow generated by a property relative to the total cash you invested. It is calculated as: CoC = Annual Cash Flow ÷ Total Cash Invested × 100. If you invested $100,000 (down payment + closing costs + repairs) and the property generates $8,000 per year in cash flow after all expenses and mortgage payments, your cash on cash return is 8%. It is the most practical return metric for leveraged real estate investors because it reflects the actual cash yield on the dollars you physically put in, not the total property value.",
  },
  {
    q: "What is a good cash on cash return?",
    a: "Most real estate investors target a cash on cash return of 8–12% as a benchmark for a solid investment. In competitive markets like San Francisco, New York, or Sydney, finding properties above 4–5% can be difficult, while in midwest US markets or secondary cities, 10–15% CoC returns are achievable. The right threshold also depends on your investment strategy: cash flow investors typically require 8%+ while appreciation investors may accept 3–5% if the location has strong price growth prospects. As a general framework: 12%+ is excellent; 8–12% is good; 4–8% is acceptable; 0–4% is poor; negative is a cash drain.",
  },
  {
    q: "What is the difference between cash on cash return and cap rate?",
    a: "Cap rate (capitalisation rate) and cash on cash return both measure investment performance, but they answer different questions. Cap rate is calculated using NOI (net operating income) divided by property value — it ignores how the property is financed. It measures the property's inherent yield as if you bought it with all cash. Cash on cash return measures your actual cash yield on the money you personally invested, after accounting for financing. When you use leverage (a mortgage), your CoC can be higher or lower than the cap rate depending on whether your loan rate is below or above the cap rate. If cap rate > interest rate, leverage amplifies returns. If cap rate < interest rate (negative leverage), borrowing hurts your CoC.",
  },
  {
    q: "How do you calculate NOI for a rental property?",
    a: "Net Operating Income (NOI) is calculated as: Effective Gross Income minus all operating expenses. Effective Gross Income = Gross Rent + Other Income − Vacancy Loss. Operating expenses include: property taxes, insurance, property management fees, maintenance and repairs reserve, HOA fees, utilities paid by the landlord, and other recurring costs. NOI does NOT include mortgage payments — it is a pre-financing metric. This is intentional, because NOI is used to value properties and compare them across different financing structures. To get cash flow, you then subtract the annual debt service (mortgage payments) from NOI.",
  },
  {
    q: "What expenses should I include in a rental property analysis?",
    a: "A thorough rental property analysis should include all of the following operating expenses: property taxes (typically 1–2% of property value annually); landlord insurance ($900–$2,000/year for a single-family home); property management fees (8–12% of gross rent if using a manager); maintenance and repairs reserve (5–10% of gross rent — many investors use the 1% rule: 1% of property value per year); capital expenditure reserve for major systems (roof, HVAC, water heater — typically another 5% of rent); vacancy reserve (5–8% for most markets); HOA fees if applicable; and any utilities paid by the landlord. Skipping the maintenance and capex reserves is the most common mistake new investors make, leading to cash flow projections that are too optimistic.",
  },
  {
    q: "What is the 1% rule in real estate?",
    a: "The 1% rule is a quick screening heuristic used by many real estate investors: a property passes the test if its monthly rent equals or exceeds 1% of the purchase price. A $300,000 property would need to rent for $3,000/month or more. Properties that pass the 1% rule often — but not always — produce positive cash flow. The rule is a starting point for screening, not a replacement for detailed analysis. In expensive markets (coastal cities, major metros), the 1% rule is virtually impossible to meet, while in cash-flow markets (midwest, southeast US), many properties exceed it. Use this calculator for a complete analysis rather than relying on the 1% rule alone.",
  },
  {
    q: "How does leverage affect cash on cash return?",
    a: "Leverage has a powerful effect on cash on cash return — it can amplify returns significantly when used correctly, but it can also destroy them when misapplied. If you buy a property with a 7% cap rate and finance it at 5% interest, your leverage is positive — you earn more on the borrowed money than it costs, amplifying your CoC return above the cap rate. If you finance at 8% on a property with a 6% cap rate, you have negative leverage — the cost of borrowing exceeds the property's yield, and your CoC return falls below the cap rate. This is why rising interest rates hurt real estate values: at higher rates, more properties have negative leverage, reducing what investors are willing to pay.",
  },
  {
    q: "What is DSCR and why do lenders care about it?",
    a: "The Debt Service Coverage Ratio (DSCR) is the ratio of a property's net operating income to its annual debt service (mortgage payments). DSCR = NOI ÷ Annual Debt Service. A DSCR of 1.0 means the property exactly covers its debt payments. Lenders typically require a DSCR of 1.20–1.25 as a buffer against vacancy, expense increases, or income drops. A DSCR of 1.25 means NOI is 25% higher than the debt payments — providing a margin of safety. Below 1.0 means the property cannot pay for itself from rental income alone. DSCR-based loans (common for investment properties) qualify borrowers based on the property's income rather than the borrower's personal income.",
  },
];

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-3xl font-black text-stone-900 mb-6 mt-16 tracking-tight">{children}</h2>;
}
function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="text-xl font-bold text-stone-800 mb-4 mt-10 tracking-tight">{children}</h3>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-stone-600 leading-relaxed mb-6 text-lg font-medium">{children}</p>;
}

export default function CashOnCashPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />

      <main className="max-w-6xl mx-auto px-6 py-16">

        {/* Hero */}
        <div className="mb-12 max-w-3xl">
          <div className="inline-flex items-center gap-3 bg-blue-50 text-blue-700 text-[11px] font-black uppercase tracking-widest px-4 py-2 rounded-full mb-6 border border-blue-100">
            <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
            CoC · Cap Rate · NOI · DSCR · GRM · Multi-year projection
          </div>
          <h1 className="text-6xl font-black text-stone-900 leading-none tracking-tighter mb-6">
            Cash on Cash Return <span className="text-blue-600 italic font-serif">Calculator</span>
          </h1>
          <p className="text-xl text-stone-500 leading-relaxed font-medium">
            The professional rental property investment analyser. Calculate cash on cash
            return, cap rate, net operating income, DSCR, and more — with a full 
            performance waterfall and multi-year projections.
          </p>
        </div>

        {/* Calculator */}
        <div className="mb-20">
          <CashOnCashCalculator />
        </div>

        {/* ── CONTENT ── */}
        <div className="max-w-4xl">
          <H2>Cash on cash return explained</H2>
          <P>
            Cash on cash return is the single most important metric for real estate investors
            who use financing to acquire properties. Unlike cap rate — which measures property
            performance independent of how it is financed — cash on cash return measures the
            actual yield on the cash dollars you personally invest in a deal. It answers the
            question every investor really wants answered: for every dollar I put in, how many
            cents come back to me in cash each year?
          </P>
          <P>
            The formula is straightforward: Annual Pre-Tax Cash Flow divided by Total Cash
            Invested, expressed as a percentage. Total Cash Invested includes your down
            payment, closing costs, upfront repairs, and any other cash you deploy to
            acquire and prepare the property. Annual Cash Flow is what remains after collecting
            rent, paying vacancy reserves, covering all operating expenses, and making your
            mortgage payments. Nothing else — no appreciation, no equity build-up — just
            the actual cash the property puts in your pocket each year.
          </P>

          <H2>Key real estate investment metrics compared</H2>
          <P>
            Professional real estate investors use several metrics in combination to evaluate
            a deal. No single number tells the whole story. Here is a complete reference for
            the metrics calculated in this tool:
          </P>

          <div className="overflow-x-auto mb-10 rounded-3xl border border-stone-200 shadow-sm overflow-hidden">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-stone-50 border-b border-stone-200">
                  <th className="text-left py-4 px-6 text-[10px] font-black uppercase tracking-widest text-stone-500">Metric</th>
                  <th className="text-left py-4 px-6 text-[10px] font-black uppercase tracking-widest text-stone-500">Formula</th>
                  <th className="text-right py-4 px-6 text-[10px] font-black uppercase tracking-widest text-stone-500">Target</th>
                  <th className="text-left py-4 px-6 text-[10px] font-black uppercase tracking-widest text-stone-500">Measures</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100">
                {METRICS_TABLE.map((row) => (
                  <tr key={row.metric} className="hover:bg-stone-50 transition-colors">
                    <td className="py-4 px-6 font-black text-stone-800 text-[11px] uppercase tracking-wider">{row.metric}</td>
                    <td className="py-4 px-6 text-xs font-mono text-stone-500">{row.formula}</td>
                    <td className="py-4 px-6 text-right">
                      <span className="text-[10px] font-black uppercase bg-emerald-50 text-emerald-700 px-2 py-1 rounded-lg">{row.good}</span>
                    </td>
                    <td className="py-4 px-6 text-stone-500 text-xs font-medium">{row.what}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <H3>The relationship between CoC return, cap rate, and leverage</H3>
          <P>
            Understanding how these three concepts interact is the key to sophisticated real
            estate analysis. The cap rate represents the property's inherent yield as if
            purchased with all cash. Your mortgage interest rate is the cost of borrowing.
            When the cap rate exceeds your mortgage rate, leverage amplifies your cash on
            cash return above the cap rate — this is called positive leverage. When the
            mortgage rate exceeds the cap rate, every dollar borrowed actually hurts your
            returns — negative leverage. In a rising interest rate environment, properties
            that previously had positive leverage can tip into negative leverage without any
            change in the property itself, which is one reason rising rates compress real
            estate values.
          </P>

          <H3>The expense categories investors most commonly underestimate</H3>
          <P>
            New real estate investors consistently underestimate operating expenses, leading
            to cash flow projections that collapse on contact with reality. The most commonly
            missed or underestimated expense categories are: maintenance and capital expenditure
            reserves (most investors budget 1–5% of rent; experienced investors budget 8–12%
            when accounting for roofs, HVAC, plumbing, and appliance replacement); property
            management fees (8–12% of gross rent, not gross collected rent — this matters
            when vacancy is high); and vacancy — many investors use 0% vacancy in optimistic
            projections when the realistic figure for most markets is 5–8%. This calculator
            includes separate fields for all of these so your projections remain grounded
            in realistic assumptions.
          </P>

          <H2>Frequently asked questions</H2>
          <div className="space-y-4 mb-16">
            {FAQS.map((faq) => (
              <details key={faq.q} className="group bg-white border border-stone-200 rounded-[2rem] overflow-hidden transition-all hover:border-blue-200 hover:shadow-xl hover:shadow-blue-500/5">
                <summary className="flex items-center justify-between cursor-pointer px-8 py-6 text-lg font-bold text-stone-800 list-none select-none transition-colors group-open:bg-blue-50/50 group-open:text-blue-700">
                  {faq.q}
                  <span className="text-stone-300 ml-6 flex-shrink-0 group-open:rotate-45 group-open:text-blue-500 transition-all duration-300 text-3xl font-light">+</span>
                </summary>
                <div className="px-8 pb-8 pt-2 text-[16px] text-stone-500 leading-relaxed font-medium">
                  {faq.a}
                </div>
              </details>
            ))}
          </div>

          <div className="mt-20 p-8 bg-stone-900 rounded-[3rem] text-stone-400 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-8 opacity-5 text-white"><Info size={120} /></div>
            <p className="text-[10px] font-black uppercase tracking-[0.3em] text-stone-500 mb-6 flex items-center gap-3">
              <span className="w-8 h-px bg-stone-700" />
              Financial Disclaimer
            </p>
            <p className="text-sm leading-relaxed relative z-10 font-medium">
              This calculator is for informational purposes only and does not constitute financial, investment, or
              tax advice. Real estate investment involves significant risk including loss of
              principal. Past performance of real estate markets does not guarantee future
              results. Appreciation and rent growth figures are assumptions — actual results
              will vary. Always conduct thorough due diligence, consult qualified professionals,
              and review actual income and expense documentation before investing.
            </p>
          </div>

          <H2>Related Real Estate Tools</H2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-20">
            {[
              { name: "Cap Rate Calculator", href: "/real-estate/cap-rate-calculator", desc: "Calculate Net Operating Income and overall property yield." },
              { name: "Rental Yield Calculator", href: "/real-estate/rental-yield-calculator", desc: "Compare gross and net yields with market benchmarks." },
              { name: "Rent vs Buy Calculator", href: "/real-estate/rent-vs-buy-calculator", desc: "Determine if it's better to rent or own over the long term." },
              { name: "Price Per Sq Ft", href: "/real-estate/price-per-square-foot-calculator", desc: "Compare property value and rent across different sizes." },
            ].map((tool) => (
              <Link
                key={tool.href}
                href={tool.href}
                className="group p-6 rounded-[2rem] border border-stone-200 bg-white hover:border-blue-300 hover:shadow-xl hover:shadow-blue-500/5 transition-all"
              >
                <h4 className="text-lg font-bold text-stone-800 group-hover:text-blue-600 transition-colors mb-2">{tool.name}</h4>
                <p className="text-sm text-stone-500 font-medium">{tool.desc}</p>
              </Link>
            ))}
          </div>
        </div>

      </main>
    </>
  );
}
