import type { SlideTemplate } from '../_types';

export const TEMPLATES: SlideTemplate[] = [
    // ── BUSINESS ──────────────────────────────────────────────────────────────
    {
        id: 'biz_pitch', name: 'Pitch Deck', categoryId: 'business',
        background: 'linear-gradient(135deg, #0d1b2a 0%, #1b3a5c 100%)',
        accentColor: '#48bfe3', tagText: 'PITCH DECK',
        defaultHeadline: 'Series A Pitch', defaultSubtitle: 'Your Company Name',
        defaultBody: 'Transforming the way businesses connect with customers through AI-powered solutions.',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    {
        id: 'biz_update', name: 'Company Update', categoryId: 'business',
        background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
        accentColor: '#e94560', tagText: 'UPDATE',
        defaultHeadline: 'Q3 2024 Update', defaultSubtitle: 'Company Newsletter',
        defaultBody: "We've hit 50K users and launched 3 new features this quarter.",
        layout: 'left', darkText: false, fontFamily: 'dm_sans',
    },
    {
        id: 'biz_report', name: 'Report', categoryId: 'business',
        background: '#f8f9fa', accentColor: '#378ADD', tagText: 'REPORT',
        defaultHeadline: 'Annual Report', defaultSubtitle: 'FY 2024',
        defaultBody: 'Key metrics, milestones, and what the year ahead holds for our team.',
        layout: 'top_accent', darkText: true, fontFamily: 'dm_sans',
    },
    // ── SOCIAL MEDIA ──────────────────────────────────────────────────────────
    {
        id: 'social_quote', name: 'Quote Card', categoryId: 'social',
        background: 'linear-gradient(135deg, #b5179e 0%, #7209b7 100%)',
        accentColor: '#ffffff', tagText: 'QUOTE',
        defaultHeadline: '"Success is not final, failure is not fatal."',
        defaultSubtitle: '— Winston Churchill', defaultBody: '',
        layout: 'centered', darkText: false, fontFamily: 'dm_serif',
    },
    {
        id: 'social_tip', name: 'Tip Card', categoryId: 'social',
        background: 'linear-gradient(135deg, #2d6a4f 0%, #40916c 100%)',
        accentColor: '#d8f3dc', tagText: 'TIP',
        defaultHeadline: 'Pro Tip #7', defaultSubtitle: 'Design',
        defaultBody: 'Always use consistent spacing — it makes everything feel intentional and polished.',
        layout: 'left', darkText: false, fontFamily: 'syne',
    },
    {
        id: 'social_announcement', name: 'Announcement', categoryId: 'social',
        background: 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)',
        accentColor: '#1a1a2e', tagText: 'ANNOUNCEMENT',
        defaultHeadline: 'BIG NEWS!', defaultSubtitle: 'Something is coming...',
        defaultBody: 'We have been working on something special. Stay tuned for the reveal on Friday!',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    // ── EDUCATIONAL ───────────────────────────────────────────────────────────
    {
        id: 'edu_howto', name: 'How-to Guide', categoryId: 'educational',
        background: '#0d1b2a', accentColor: '#5e60ce', tagText: 'HOW-TO',
        defaultHeadline: 'How to Write Better Headlines', defaultSubtitle: 'Step 1 of 5',
        defaultBody: 'Start with a number or power word. Keep it under 70 characters. Make a promise you can keep.',
        layout: 'left', darkText: false, fontFamily: 'dm_sans',
    },
    {
        id: 'edu_tutorial', name: 'Tutorial', categoryId: 'educational',
        background: 'linear-gradient(135deg, #480ca8 0%, #3a0ca3 100%)',
        accentColor: '#4cc9f0', tagText: 'TUTORIAL',
        defaultHeadline: 'CSS Grid in 5 Minutes', defaultSubtitle: 'Tutorial',
        defaultBody: 'grid-template-columns lets you define the number and size of columns in your layout.',
        layout: 'centered', darkText: false, fontFamily: 'space_mono',
    },
    {
        id: 'edu_fact', name: 'Fun Fact', categoryId: 'educational',
        background: 'linear-gradient(135deg, #0f3460 0%, #16213e 100%)',
        accentColor: '#e94560', tagText: 'FACT',
        defaultHeadline: 'Did you know?', defaultSubtitle: 'Science',
        defaultBody: 'Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs.',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    // ── MARKETING ─────────────────────────────────────────────────────────────
    {
        id: 'mkt_launch', name: 'Product Launch', categoryId: 'marketing',
        background: 'linear-gradient(135deg, #7400b8 0%, #6930c3 100%)',
        accentColor: '#48bfe3', tagText: 'NEW',
        defaultHeadline: 'Introducing Pro Plan', defaultSubtitle: 'Available now',
        defaultBody: 'Everything you need to grow — unlimited projects, priority support, advanced analytics.',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    {
        id: 'mkt_promo', name: 'Promotion', categoryId: 'marketing',
        background: 'linear-gradient(135deg, #ff6b35 0%, #e94560 100%)',
        accentColor: '#ffffff', tagText: 'PROMO',
        defaultHeadline: '50% OFF', defaultSubtitle: 'Limited time offer',
        defaultBody: 'Use code LAUNCH50 at checkout. Offer ends Sunday at midnight.',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    {
        id: 'mkt_sale', name: 'Sale', categoryId: 'marketing',
        background: '#1a1a2e', accentColor: '#EF9F27', tagText: 'SALE',
        defaultHeadline: 'Flash Sale', defaultSubtitle: 'Today only',
        defaultBody: 'Our biggest discount ever on all annual plans. Do not miss this.',
        layout: 'left', darkText: false, fontFamily: 'dm_sans',
    },
    // ── PERSONAL ──────────────────────────────────────────────────────────────
    {
        id: 'per_story', name: 'Story', categoryId: 'personal',
        background: 'linear-gradient(135deg, #2d6a4f 0%, #1b4332 100%)',
        accentColor: '#74c69d', tagText: 'STORY',
        defaultHeadline: 'My Entrepreneurship Journey', defaultSubtitle: 'From zero to $1M ARR',
        defaultBody: 'Two years ago I had an idea. No investors. No team. Just a laptop and a vision.',
        layout: 'left', darkText: false, fontFamily: 'dm_serif',
    },
    {
        id: 'per_testimonial', name: 'Testimonial', categoryId: 'personal',
        background: '#0d1b2a', accentColor: '#48bfe3', tagText: 'TESTIMONIAL',
        defaultHeadline: '"This tool 10x\'d our output"', defaultSubtitle: '— Sarah M., Head of Marketing',
        defaultBody: 'We went from 2 posts a week to 20. The ROI has been incredible.',
        layout: 'centered', darkText: false, fontFamily: 'dm_serif',
    },
    {
        id: 'per_lifestyle', name: 'Lifestyle', categoryId: 'personal',
        background: 'linear-gradient(135deg, #b5179e 0%, #560bad 100%)',
        accentColor: '#f8c8e8', tagText: 'LIFESTYLE',
        defaultHeadline: 'Morning Routine', defaultSubtitle: '5am club',
        defaultBody: 'Hydrate. Move. Journal. These 30 minutes set the tone for my entire day.',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    // ── LISTS & TIPS ──────────────────────────────────────────────────────────
    {
        id: 'list_step', name: 'Step-by-Step', categoryId: 'lists',
        background: '#0f3460', accentColor: '#48bfe3', tagText: 'GUIDE',
        defaultHeadline: '5 Steps to Launch', defaultSubtitle: 'Start today',
        defaultBody: '1. Define your MVP\n2. Build in public\n3. Get 10 beta users\n4. Collect feedback\n5. Iterate fast',
        layout: 'left', darkText: false, fontFamily: 'dm_sans',
    },
    {
        id: 'list_numbered', name: 'Numbered List', categoryId: 'lists',
        background: 'linear-gradient(135deg, #1a1a2e 0%, #533483 100%)',
        accentColor: '#AFA9EC', tagText: 'LIST',
        defaultHeadline: 'Top 7 Tools for 2024', defaultSubtitle: 'Productivity',
        defaultBody: 'Notion · Figma · Linear · Raycast · Arc · Superhuman · Fathom',
        layout: 'left', darkText: false, fontFamily: 'dm_sans',
    },
    {
        id: 'list_checklist', name: 'Checklist', categoryId: 'lists',
        background: '#1b4332', accentColor: '#74c69d', tagText: 'CHECKLIST',
        defaultHeadline: 'Launch Checklist', defaultSubtitle: 'Are you ready?',
        defaultBody: '✓ Landing page live\n✓ Email sequence set\n✓ Analytics connected\n○ Press outreach\n○ Social scheduled',
        layout: 'left', darkText: false, fontFamily: 'space_mono',
    },
    // ── BEFORE / AFTER ────────────────────────────────────────────────────────
    {
        id: 'ba_comparison', name: 'Comparison', categoryId: 'before_after',
        background: 'linear-gradient(135deg, #0d1b2a 0%, #1b2838 100%)',
        accentColor: '#48bfe3', tagText: 'BEFORE / AFTER',
        defaultHeadline: 'Then vs Now', defaultSubtitle: '12 months apart',
        defaultBody: 'Before: 200 followers, 0 revenue\nAfter: 42K followers, $180K ARR',
        layout: 'split', darkText: false, fontFamily: 'syne',
    },
    {
        id: 'ba_transformation', name: 'Transformation', categoryId: 'before_after',
        background: 'linear-gradient(135deg, #b5179e 0%, #7209b7 100%)',
        accentColor: '#ffffff', tagText: 'TRANSFORMATION',
        defaultHeadline: 'The Transformation', defaultSubtitle: 'Real results',
        defaultBody: 'Lost 18kg in 6 months — not through restriction, but through sustainable habits.',
        layout: 'centered', darkText: false, fontFamily: 'dm_serif',
    },
    {
        id: 'ba_split', name: 'Split View', categoryId: 'before_after',
        background: '#0f3460', accentColor: '#EF9F27', tagText: 'SPLIT',
        defaultHeadline: 'Old vs New Way', defaultSubtitle: 'Workflow redesign',
        defaultBody: 'Old: 14 steps, 3 tools, 2 hours\nNew: 3 steps, 1 tool, 15 minutes',
        layout: 'split', darkText: false, fontFamily: 'dm_sans',
    },
    // ── STATISTICS ────────────────────────────────────────────────────────────
    {
        id: 'stat_infographic', name: 'Infographic', categoryId: 'statistics',
        background: 'linear-gradient(135deg, #7400b8 0%, #3a0ca3 100%)',
        accentColor: '#4cc9f0', tagText: 'STATS',
        defaultHeadline: 'Social Media 2024', defaultSubtitle: 'Key statistics',
        defaultBody: '4.9B users · 145 min/day avg · 62% buy after story ad',
        layout: 'centered', darkText: false, fontFamily: 'syne',
    },
    {
        id: 'stat_data', name: 'Data Visual', categoryId: 'statistics',
        background: '#0d1b2a', accentColor: '#1D9E75', tagText: 'DATA',
        defaultHeadline: 'Growth Metrics', defaultSubtitle: 'Q1–Q4 2024',
        defaultBody: 'MRR ↑ 340% · Churn ↓ 2.1% · NPS 72 · CAC $48',
        layout: 'left', darkText: false, fontFamily: 'space_mono',
    },
    {
        id: 'stat_chart', name: 'Chart Card', categoryId: 'statistics',
        background: 'linear-gradient(135deg, #1b2838 0%, #0d1b2a 100%)',
        accentColor: '#48bfe3', tagText: 'CHART',
        defaultHeadline: 'Revenue Growth', defaultSubtitle: 'Monthly recurring revenue',
        defaultBody: 'Jan $12K → Jun $67K → Dec $180K',
        layout: 'left', darkText: false, fontFamily: 'syne',
    },
];