import type { FreeToolMeta } from "@/types/tools";
import { EXACT_TOOL_REGISTRY } from "@/lib/tools/exact-catalog";
import { IMAGE_TOOL_REGISTRY } from "@/lib/tools/image-catalog";
import { PDF_TOOL_REGISTRY } from "@/lib/tools/pdf-catalog";
import { TAILWIND_TOOL_REGISTRY } from "@/lib/tools/tailwind-catalog";

export const FREE_TOOL_CATEGORY_ROUTES: Record<FreeToolMeta["category"], string> = {
  AI: "/ai",
  Converter: "/converter",
  Finance: "/finance",
  Image: "/image",
  PDF: "/pdf",
  "Real Estate": "/real-estate",
  Tailwind: "/tailwind",
  Text: "/text",
  Utility: "/utility",
  Construction: "/construction",
  Health: "/health",
};

export const FREE_TOOLS: FreeToolMeta[] = [
  {
    name: "Expected Goals (xG) Calculator",
    href: "/utility/xg-expected-goals-calculator",
    description:
      "Free xG calculator for football and soccer: interactive pitch, heatmap, and shot parameters for expected goals modelling.",
    category: "Utility",
    icon: "XG",
  },
  {
    name: "Free Social Media Carousel Builder",
    href: "/utility/free-social-media-carousel-builder",
    description: "Create six-slide social media carousels with AI drafting, editable templates, mobile controls, and PNG export.",
    category: "Utility",
    icon: "SLDS",
  },
  {
    name: "AI Humanizer",
    href: "/ai/ai-humanizer",
    description: "Rewrite AI-generated text to sound natural and human, with a short queue flow and no sign-up.",
    category: "AI",
    icon: "HUMN",
  },
  {
    name: "Salary Calculator",
    href: "/finance/salary-calculator",
    description: "Estimate salary after tax, take-home pay, and employer cost across major countries.",
    category: "Finance",
    icon: "PAY",
  },
  {
    name: "UAE Salary Calculator",
    href: "/finance/uae-salary-calculator",
    description: "Calculate monthly UAE net salary from basic salary, allowances, overtime, and deductions.",
    category: "Finance",
    icon: "AED",
  },
  {
    name: "UAE Gratuity Calculator",
    href: "/finance/uae-gratuity-calculator",
    description: "Estimate UAE end-of-service gratuity from monthly basic salary, contract dates, and unpaid leave.",
    category: "Finance",
    icon: "EOS",
  },
  {
    name: "UAE Visa Cost Calculator",
    href: "/finance/uae-visa-cost-calculator",
    description: "Estimate total UAE visa fees including government charges, medical, Emirates ID, and typing centre costs.",
    category: "Finance",
    icon: "VISA",
  },
  {
    name: "Mortgage Calculator",
    href: "/finance/mortgage-calculator",
    description: "Calculate monthly home loan payments with down payment, property tax, and insurance.",
    category: "Finance",
    icon: "MTG",
  },
  {
    name: "DTI Calculator",
    href: "/finance/dti-calculator",
    description: "Calculate debt-to-income ratio from gross monthly income and recurring monthly debt payments using the CFPB definition.",
    category: "Finance",
    icon: "DTI",
  },
  {
    name: "EMI Calculator",
    href: "/finance/emi-calculator",
    description: "Calculate monthly loan instalments for home, car, and personal loans.",
    category: "Finance",
    icon: "EMI",
  },
  {
    name: "Car Loan Calculator",
    href: "/finance/car-loan-calculator",
    description: "Calculate monthly payments for new and used car loans with down payment and trade-in value.",
    category: "Finance",
    icon: "AUTO",
  },
  {
    name: "Credit Card Payoff Calculator",
    href: "/finance/credit-card-payoff-calculator",
    description: "Estimate payoff time, total interest, and the payment needed to clear a credit card balance in 36 months.",
    category: "Finance",
    icon: "CARD",
  },
  {
    name: "Discount Calculator",
    href: "/finance/discount-calculator",
    description: "Calculate final price after discount or reverse-calculate the percent off from original and sale price.",
    category: "Finance",
    icon: "SALE",
  },
  {
    name: "VAT Calculator",
    href: "/finance/vat-calculator",
    description: "Add VAT to a net price or remove VAT from a gross price with country presets and custom rates.",
    category: "Finance",
    icon: "VAT",
  },
  {
    name: "GST Calculator",
    href: "/finance/gst-calculator",
    description: "Calculate Singapore GST using the current 9% standard rate and the official IRAS distinction between standard-rated, zero-rated, and exempt supplies.",
    category: "Finance",
    icon: "GST",
  },
  {
    name: "Profit Margin Calculator",
    href: "/finance/profit-margin-calculator",
    description: "Calculate margin, markup, gross profit, and selling price from cost in one pricing calculator.",
    category: "Finance",
    icon: "MRG",
  },
  {
    name: "Compound Interest Calculator",
    href: "/finance/compound-interest-calculator",
    description: "Project future value, contributions, and compound growth with optional inflation adjustment.",
    category: "Finance",
    icon: "CAGR",
  },
  {
    name: "Savings Goal Calculator",
    href: "/finance/savings-goal-calculator",
    description: "Calculate the monthly contribution needed to reach a savings target from your current balance, time horizon, and return assumption.",
    category: "Finance",
    icon: "SAVE",
  },
  {
    name: "Percentage Calculator",
    href: "/finance/percentage-calculator",
    description: "Instantly calculate percentages, percentage changes, and value proportions without formulas.",
    category: "Finance",
    icon: "PCT",
  },
  {
    name: "Click-Through Rate Calculator",
    href: "/finance/click-through-rate-calculator",
    description: "Calculate CTR from clicks and impressions, and estimate the clicks needed to hit a target click-through rate.",
    category: "Finance",
    icon: "CTR",
  },
  {
    name: "CPC / CPM Calculator",
    href: "/finance/cpc-cpm-calculator",
    description: "Calculate cost per click, cost per 1,000 impressions, and the spend needed to reach target traffic or reach goals.",
    category: "Finance",
    icon: "CPC",
  },
  {
    name: "ROI Calculator",
    href: "/finance/roi-calculator",
    description: "Calculate return on investment, net profit, cost basis, and annualized return from money in and money out.",
    category: "Finance",
    icon: "ROI",
  },
  {
    name: "Foreign Exchange Fee Calculator",
    href: "/finance/foreign-exchange-fee-calculator",
    description: "Convert currencies using a live reference rate and estimate the final amount received after a bank charge percentage.",
    category: "Finance",
    icon: "FX",
  },
  {
    name: "Loan Payoff Calculator",
    href: "/finance/loan-payoff-calculator",
    description: "Calculate scheduled payments, early payoff timing, months saved, and interest saved from extra monthly principal.",
    category: "Finance",
    icon: "PAY",
  },
  {
    name: "Net Worth Calculator",
    href: "/finance/net-worth-calculator",
    description: "Calculate total assets, total liabilities, liquid assets, and net worth from a personal balance sheet.",
    category: "Finance",
    icon: "NW",
  },
  {
    name: "Budget Planner",
    href: "/finance/budget-planner",
    description: "Plan monthly income, expenses, savings, and category shares to see total cash flow clearly.",
    category: "Finance",
    icon: "BGT",
  },
  {
    name: "Freelancer Rate Calculator",
    href: "/finance/freelancer-rate-calculator",
    description: "Estimate hourly rate, day rate, and annual revenue target from income goals, overhead, taxes, and billable hours.",
    category: "Finance",
    icon: "RATE",
  },
  {
    name: "Payroll Tax Calculator",
    href: "/finance/payroll-tax-calculator",
    description: "Calculate 2026 U.S. federal payroll taxes including Social Security, Medicare, Additional Medicare, and FUTA using published wage-base rules.",
    category: "Finance",
    icon: "TAX",
  },
  {
    name: "Employee Cost Calculator",
    href: "/finance/employee-cost-calculator",
    description: "Estimate total annual employer cost from salary, federal payroll taxes, annual benefits, and retirement contributions.",
    category: "Finance",
    icon: "EMP",
  },
  {
    name: "Churn Rate Calculator",
    href: "/finance/churn-rate-calculator",
    description: "Calculate customer churn rate, revenue churn rate, ending customers, and net customer change from one reporting period.",
    category: "Finance",
    icon: "CHRN",
  },
  {
    name: "Customer Lifetime Value Calculator",
    href: "/finance/customer-lifetime-value-calculator",
    description: "Calculate annual customer gross profit and lifetime value from revenue per purchase, margin, purchase frequency, and customer lifespan.",
    category: "Finance",
    icon: "CLV",
  },
  {
    name: "Invoice Generator",
    href: "/finance/invoice-generator",
    description: "Draft line items and calculate invoice subtotal, discount, tax, and total in one simple invoice builder.",
    category: "Finance",
    icon: "INV",
  },
  {
    name: "Salary to Hourly Calculator",
    href: "/finance/salary-to-hourly-calculator",
    description: "Convert your annual salary to an hourly wage, daily rate, and monthly pay breakdown.",
    category: "Finance",
    icon: "PAY",
  },
  {
    name: "Rental Yield Calculator",
    href: "/real-estate/rental-yield-calculator",
    description: "Calculate gross yield, net yield, and net operating income from property price, rent, and annual costs.",
    category: "Real Estate",
    icon: "YLD",
  },
  {
    name: "Cap Rate Calculator",
    href: "/real-estate/cap-rate-calculator",
    description: "Calculate cap rate and NOI from property value, rent, and annual operating expenses.",
    category: "Real Estate",
    icon: "CAP",
  },
  {
    name: "Rent Affordability Calculator",
    href: "/real-estate/rent-affordability-calculator",
    description: "Estimate a monthly rent budget from income, debts, utilities, and target housing ratio.",
    category: "Real Estate",
    icon: "RENT",
  },
  {
    name: "Closing Costs Calculator",
    href: "/real-estate/closing-costs-calculator",
    description: "Estimate closing costs and total cash needed from purchase price, down payment, and fees.",
    category: "Real Estate",
    icon: "CLS",
  },
  {
    name: "Price per Square Foot Calculator",
    href: "/real-estate/price-per-square-foot-calculator",
    description: "Calculate price per square foot or square metre from total price and property area.",
    category: "Real Estate",
    icon: "PSF",
  },
  {
    name: "Rent vs Buy Calculator",
    href: "/real-estate/rent-vs-buy-calculator",
    description: "Compare renting and buying costs across the years you expect to stay in the property.",
    category: "Real Estate",
    icon: "BUY",
  },
  {
    name: "BMI Calculator",
    href: "/utility/bmi-calculator",
    description: "Calculate Body Mass Index (BMI) and find your ideal weight range using metric or imperial units.",
    category: "Utility",
    icon: "BMI",
  },
  {
    name: "Age Calculator",
    href: "/utility/age-calculator",
    description: "Calculate exact age in years, months, days, weeks, and total days from a birth date to any target date.",
    category: "Utility",
    icon: "AGE",
  },
  {
    name: "Tip Calculator",
    href: "/utility/tip-calculator",
    description: "Calculate gratuity, full bill total, and the per-person share from a bill amount and tip percentage.",
    category: "Utility",
    icon: "TIP",
  },
  {
    name: "Free CV Resume Builder",
    href: "/utility/free-cv-resume-builder",
    description: "Build a resume online for free with editable sections, multiple templates, browser autosave, and print-to-PDF export.",
    category: "Utility",
    icon: "CV",
  },
  {
    name: "Robots.txt Generator",
    href: "/utility/robots-txt-generator",
    description: "Generate a robots.txt file with user-agent rules, sitemap reference, and optional crawl-delay.",
    category: "Utility",
    icon: "BOT",
  },
  {
    name: "Sitemap Generator",
    href: "/utility/sitemap-generator",
    description: "Generate a basic sitemap.xml file from a site URL and a list of paths or full URLs.",
    category: "Utility",
    icon: "MAP",
  },
  {
    name: "JWT Decoder",
    href: "/utility/jwt-decoder",
    description: "Decode JWT header and payload segments locally in the browser for debugging and inspection.",
    category: "Utility",
    icon: "JWT",
  },
  {
    name: "Scientific Calculator",
    href: "/utility/scientific-calculator",
    description: "Evaluate arithmetic, trig functions, logarithms, factorials, and scientific expressions directly in the browser.",
    category: "Utility",
    icon: "SCI",
  },
  {
    name: "Quadratic Equation Solver",
    href: "/utility/quadratic-equation-solver",
    description: "Solve quadratic equations and inspect roots, discriminant, axis of symmetry, and vertex coordinates.",
    category: "Utility",
    icon: "QUAD",
  },
  {
    name: "Statistics Calculator",
    href: "/utility/statistics-calculator",
    description: "Calculate mean, median, mode, variance, and standard deviation from a list of numbers.",
    category: "Utility",
    icon: "STAT",
  },
  {
    name: "Probability Calculator",
    href: "/utility/probability-calculator",
    description: "Calculate basic probability, combinations, permutations, and exact binomial probability from common inputs.",
    category: "Utility",
    icon: "PROB",
  },
  {
    name: "Logarithm Calculator",
    href: "/utility/logarithm-calculator",
    description: "Calculate logarithms with a custom base and compare them to natural log and common log values.",
    category: "Utility",
    icon: "LOG",
  },
  {
    name: "UTM Link Builder",
    href: "/utility/utm-link-builder",
    description: "Build trackable campaign URLs with custom UTM parameters for Google Analytics.",
    category: "Utility",
    icon: "LINK",
  },
  {
    name: "QR Code Generator",
    href: "/utility/qr-code-generator",
    description: "Create and download static QR codes with custom colors and zero expiry limits.",
    category: "Utility",
    icon: "QR",
  },
  {
    name: "Barcode Generator",
    href: "/utility/barcode-generator",
    description: "Instantly create CODE128, UPC, and EAN barcodes and download high-quality PNGs.",
    category: "Utility",
    icon: "CODE",
  },
  {
    name: "QR Code Scanner",
    href: "/utility/qr-code-scanner",
    description: "Scan QR codes using your device camera or upload an image to decode web links instantly.",
    category: "Utility",
    icon: "CAM",
  },
  {
    name: "Barcode Scanner",
    href: "/utility/barcode-scanner",
    description: "Use your webcam or phone to scan 1D retail product barcodes and look them up online.",
    category: "Utility",
    icon: "SCAN",
  },
  {
    name: "Pomodoro Timer",
    href: "/utility/pomodoro-timer",
    description: "Boost productivity with a clean focus timer featuring 25-minute sprints and audio alarms.",
    category: "Utility",
    icon: "TIME",
  },
  {
    name: "Voice Dictation",
    href: "/text/voice-dictation",
    description: "Convert your voice into text in real-time using your browser's microphone natively.",
    category: "Text",
    icon: "MIC",
  },
  {
    name: "Meta Tags Generator",
    href: "/utility/meta-tags-generator",
    description: "Preview and generate SEO HTML Meta Tags and social media Open Graph cards.",
    category: "Utility",
    icon: "META",
  },
  {
    name: "Down Payment Calculator",
    href: "/real-estate/down-payment-calculator",
    description: "Work out the down payment amount, loan amount, and loan-to-value ratio from a home price and deposit percentage.",
    category: "Real Estate",
    icon: "DWN",
  },
  {
    name: "Mortgage Refinance Calculator",
    href: "/real-estate/mortgage-refinance-calculator",
    description: "Compare current and refinanced mortgage payments, break-even timing, and total remaining cost.",
    category: "Real Estate",
    icon: "REFI",
  },
  {
    name: "Rental Cash Flow Calculator",
    href: "/real-estate/rental-cash-flow-calculator",
    description: "Estimate monthly and annual rental cash flow after vacancy, mortgage costs, and operating expenses.",
    category: "Real Estate",
    icon: "FLOW",
  },
  {
    name: "Home Buying Budget Calculator",
    href: "/real-estate/home-buying-budget-calculator",
    description: "Estimate a realistic home budget from income, debt, down payment, ownership costs, and mortgage assumptions.",
    category: "Real Estate",
    icon: "BUD",
  },
  {
    name: "Lease Escalation Calculator",
    href: "/real-estate/lease-escalation-calculator",
    description: "Project rent increases across a lease term from the starting rent, annual escalation rate, and number of years.",
    category: "Real Estate",
    icon: "ESC",
  },
  {
    name: "Security Deposit Calculator",
    href: "/real-estate/security-deposit-calculator",
    description: "Estimate deposit amount and move-in cash from monthly rent, advance rent, and admin fees.",
    category: "Real Estate",
    icon: "DEP",
  },
  {
    name: "Property Management Fee Calculator",
    href: "/real-estate/property-management-fee-calculator",
    description: "Estimate management fees, leasing fees, and owner net income from a rental property's annual rent.",
    category: "Real Estate",
    icon: "PMF",
  },
  {
    name: "Stamp Duty Calculator",
    href: "/real-estate/stamp-duty-calculator",
    description: "Estimate stamp duty, legal costs, and registration fees from a property purchase price and duty rate.",
    category: "Real Estate",
    icon: "DUTY",
  },
  {
    name: "UK Stamp Duty Calculator",
    href: "/real-estate/uk-stamp-duty-calculator",
    description: "Calculate England and Northern Ireland SDLT with current residential bands, first-time relief, and surcharge options.",
    category: "Real Estate",
    icon: "UKSD",
  },
  {
    name: "Singapore Property Stamp Duty Calculator",
    href: "/real-estate/singapore-property-stamp-duty-calculator",
    description: "Calculate Singapore BSD, ABSD, and SSD using current buyer profiles and seller-duty regimes.",
    category: "Real Estate",
    icon: "SGSD",
  },
  {
    name: "Singapore Buyer's Stamp Duty Calculator",
    href: "/real-estate/singapore-buyers-stamp-duty-calculator",
    description: "Calculate Singapore BSD and ABSD using the current residential buyer profile rates.",
    category: "Real Estate",
    icon: "SGB",
  },
  {
    name: "Singapore Seller's Stamp Duty Calculator",
    href: "/real-estate/singapore-sellers-stamp-duty-calculator",
    description: "Estimate Singapore SSD from the acquisition date, disposal date, and current residential seller-duty rules.",
    category: "Real Estate",
    icon: "SGS",
  },
  {
    name: "NYC Transfer Tax Calculator",
    href: "/real-estate/nyc-transfer-tax-calculator",
    description: "Estimate New York City real property transfer tax from the transfer price and property type.",
    category: "Real Estate",
    icon: "NYC",
  },
  {
    name: "Dubai Property Transfer Fee Calculator",
    href: "/real-estate/dubai-property-transfer-fee-calculator",
    description: "Estimate Dubai Land Department transfer fees, trustee fees, and title-related charges from the sale price.",
    category: "Real Estate",
    icon: "DXB",
  },
  {
    name: "Scotland LBTT Calculator",
    href: "/real-estate/scotland-lbtt-calculator",
    description: "Calculate Scottish residential LBTT with first-time buyer relief and the Additional Dwelling Supplement.",
    category: "Real Estate",
    icon: "SCT",
  },
  {
    name: "Wales LTT Calculator",
    href: "/real-estate/wales-ltt-calculator",
    description: "Calculate Welsh residential Land Transaction Tax using the standard or higher residential rates.",
    category: "Real Estate",
    icon: "WLS",
  },
  {
    name: "Hong Kong Stamp Duty Calculator",
    href: "/real-estate/hong-kong-stamp-duty-calculator",
    description: "Estimate Hong Kong residential ad valorem stamp duty using the current Scale 2 rate schedule.",
    category: "Real Estate",
    icon: "HKG",
  },
  {
    name: "Dubai Mortgage Registration Calculator",
    href: "/real-estate/dubai-mortgage-registration-calculator",
    description: "Estimate Dubai mortgage registration fees from the mortgage amount using the published DLD fee structure.",
    category: "Real Estate",
    icon: "DMR",
  },
  {
    name: "Dubai Service Charge Calculator",
    href: "/real-estate/dubai-service-charge-calculator",
    description: "Estimate Dubai annual service charges from the title deed area and the approved DLD service charge rate per square foot.",
    category: "Real Estate",
    icon: "DSC",
  },
  {
    name: "Word Frequency Counter",
    href: "/text/word-frequency",
    description: "Analyze repeated words, filter stop words, and surface the most-used terms in any text block.",
    category: "Text",
    icon: "WORD",
  },
  {
    name: "Character Counter",
    href: "/text/character-counter",
    description: "Count characters and optimize text for SEO titles, meta descriptions, social posts, ads, and custom limits.",
    category: "Text",
    icon: "CHAR",
  },
  {
    name: "Case Converter",
    href: "/text/case-converter",
    description: "Convert text into uppercase, lowercase, title case, sentence case, camelCase, PascalCase, kebab-case, and snake_case.",
    category: "Text",
    icon: "CASE",
  },
  {
    name: "Duplicate Word Finder",
    href: "/text/duplicate-word-finder",
    description: "Find repeated words, duplicate counts, and overused terms quickly in any text block.",
    category: "Text",
    icon: "DUP",
  },
  {
    name: "Em Dash Remover",
    href: "/text/em-dash-remover",
    description: "Replace em dashes and en dashes with a comma, hyphen, space, or nothing in one pass.",
    category: "Text",
    icon: "DASH",
  },
  {
    name: "Strikethrough Text",
    href: "/text/strikethrough-text",
    description: "Generate strike-through, underline, double underline, dotted, and wave-style Unicode text effects.",
    category: "Text",
    icon: "LINE",
  },
  {
    name: "Reverse Text Generator",
    href: "/text/reverse-text-generator",
    description: "Reverse full text, reverse word order, or reverse each word instantly in one text utility.",
    category: "Text",
    icon: "REV",
  },
  {
    name: "Morse Code Translator",
    href: "/text/morse-code-translator",
    description: "Translate text to Morse code and Morse code back to text with support for letters, numbers, and punctuation.",
    category: "Text",
    icon: "MORSE",
  },
  {
    name: "Binary Code Translator",
    href: "/text/binary-code-translator",
    description: "Translate text to binary and binary back to text with 8-bit byte conversion and validation.",
    category: "Text",
    icon: "BIN",
  },
  {
    name: "ASCII Art Generator",
    href: "/text/ascii-art-generator",
    description: "Generate FIGlet-style ASCII art banners with a curated font set and layout controls.",
    category: "Text",
    icon: "ASCII",
  },
  {
    name: "Image to Text OCR",
    href: "/text/convert-image-to-text",
    description: "Extract, clean, copy, and download editable text from JPG, PNG, WEBP, and BMP images with OCR.",
    category: "Text",
    icon: "OCR",
  },
  {
    name: "Word Cloud Generator",
    href: "/text/word-cloud-generator",
    description: "Generate a word cloud from text with frequency sizing, filters, and copyable top-word output.",
    category: "Text",
    icon: "CLOUD",
  },
  {
    name: "Remove Duplicate Lines",
    href: "/text/remove-duplicate-lines",
    description: "Remove repeated lines from multiline text while keeping the first occurrence of each line.",
    category: "Text",
    icon: "LINES",
  },
  {
    name: "Concrete Volume Calculator",
    href: "/construction/concrete-volume-calculator",
    description: "Calculate the volume and number of bags of concrete needed for slabs, footings, and columns.",
    category: "Construction",
    icon: "CONC",
  },
  {
    name: "Paint Coverage Calculator",
    href: "/construction/paint-coverage-calculator",
    description: "Calculate the number of paint gallons needed to cover walls and ceilings based on dimensions and coats.",
    category: "Construction",
    icon: "PNT",
  },
  {
    name: "Flooring Material Calculator",
    href: "/construction/flooring-material-calculator",
    description: "Calculate total square footage and boxes of flooring material needed, accounting for waste.",
    category: "Construction",
    icon: "FLR",
  },
  {
    name: "Roofing Material Calculator",
    href: "/construction/roofing-material-calculator",
    description: "Calculate squares of shingles and bundles needed for your roof based on base area and pitch.",
    category: "Construction",
    icon: "ROOF",
  },
  {
    name: "Brick / Block Quantity Calculator",
    href: "/construction/brick-block-quantity-calculator",
    description: "Calculate the total number of bricks or concrete blocks required for a wall project including mortar allowance.",
    category: "Construction",
    icon: "BRK",
  },
  {
    name: "Wallpaper Calculator",
    href: "/construction/wallpaper-calculator",
    description: "Calculate how many rolls of wallpaper you need for your room dimensions and roll size.",
    category: "Construction",
    icon: "WALL",
  },
  {
    name: "Gravel / Mulch Volume Calculator",
    href: "/construction/gravel-mulch-volume-calculator",
    description: "Calculate the volume and weight of gravel, mulch, or dirt needed for landscaping projects.",
    category: "Construction",
    icon: "GRV",
  },
  {
    name: "Room Area Calculator",
    href: "/construction/room-area-calculator",
    description: "Calculate the total square footage of a room, adding alcoves and subtracting windows and doors.",
    category: "Construction",
    icon: "AREA",
  },
  {
    name: "Fence Material Calculator",
    href: "/construction/fence-material-calculator",
    description: "Calculate the number of posts, rails, and pickets needed for a wooden fence.",
    category: "Construction",
    icon: "FNC",
  },
  {
    name: "Staircase Rise and Run Calculator",
    href: "/construction/staircase-calculator",
    description: "Calculate stringer length, number of steps, rise, and run for building a continuous staircase.",
    category: "Construction",
    icon: "STR",
  },
  {
    name: "BMR Calculator",
    href: "/health/bmr-calculator",
    description: "Calculate your Basal Metabolic Rate using the Mifflin-St Jeor Equation.",
    category: "Health",
    icon: "H-BMR",
  },
  {
    name: "Calorie Calculator (TDEE)",
    href: "/health/calorie-calculator",
    description: "Estimate your Total Daily Energy Expenditure based on your activity level.",
    category: "Health",
    icon: "H-CAL",
  },
  {
    name: "Macro Calculator",
    href: "/health/macro-calculator",
    description: "Break down your calories into Protein, Carbs, and Fats based on your goals.",
    category: "Health",
    icon: "H-MAC",
  },
  {
    name: "Ideal Body Weight Calculator",
    href: "/health/ideal-weight-calculator",
    description: "Find your target weight range using the Devine, Robinson, Miller, and Hamwi formulas.",
    category: "Health",
    icon: "H-IBW",
  },
  {
    name: "Body Fat Percentage Estimator",
    href: "/health/body-fat-calculator",
    description: "Estimate your body fat percentage using US Navy circumference method.",
    category: "Health",
    icon: "H-BF",
  },
  {
    name: "Waist-to-Hip Ratio Calculator",
    href: "/health/waist-to-hip-calculator",
    description: "Assess your health risk factor based on your waist and hip measurements.",
    category: "Health",
    icon: "H-WHR",
  },
  {
    name: "Water Intake Calculator",
    href: "/health/water-intake-calculator",
    description: "Calculate how much water you should drink daily based on weight and exercise.",
    category: "Health",
    icon: "H-H2O",
  },
  {
    name: "Blood Pressure Category Checker",
    href: "/health/blood-pressure-calculator",
    description: "Check your blood pressure category and understand what the numbers mean.",
    category: "Health",
    icon: "H-BP",
  },
  {
    name: "Glucose Converter",
    href: "/health/glucose-converter",
    description: "Convert blood glucose and blood sugar readings between mg/dL and mmol/L with quick target references.",
    category: "Health",
    icon: "H-GLU",
  },
  {
    name: "Coffee Caffeine Intake Tracker",
    href: "/health/caffeine-calculator",
    description: "Track your total caffeine consumption from coffee, tea, and sodas.",
    category: "Health",
    icon: "H-CAF",
  },
  {
    name: "Pregnancy Due Date Calculator",
    href: "/health/pregnancy-due-date-calculator",
    description: "Estimate your baby due date based on your last menstrual period or conception date.",
    category: "Health",
    icon: "H-PREG",
  },
  {
    name: "Ovulation / Fertility Window Calculator",
    href: "/health/ovulation-calculator",
    description: "Find your most fertile days and estimated ovulation date based on your cycle.",
    category: "Health",
    icon: "H-OVU",
  },
  {
    name: "Sleep Calculator",
    href: "/health/sleep-calculator",
    description: "Calculate the best time to wake up or go to sleep based on 90-minute sleep cycles.",
    category: "Health",
    icon: "H-ZZZ",
  },
  {
    name: "Intermittent Fasting Schedule Generator",
    href: "/health/intermittent-fasting-calculator",
    description: "Generate a personalized fasting and eating schedule for 16:8, 18:6, or 20:4 methods.",
    category: "Health",
    icon: "H-FAST",
  },
  {
    name: "One Rep Max Calculator",
    href: "/health/one-rep-max-calculator",
    description: "Estimate your one-rep max (1RM) for any lift based on weight and reps.",
    category: "Health",
    icon: "H-1RM",
  },
  {
    name: "Running Pace Calculator",
    href: "/health/running-pace-calculator",
    description: "Calculate your pace per mile or kilometer for any distance.",
    category: "Health",
    icon: "H-RUN",
  },
  {
    name: "VO2 Max Estimator",
    href: "/health/vo2-max-calculator",
    description: "Estimate your maximum oxygen consumption using various fitness tests.",
    category: "Health",
    icon: "H-VO2",
  },
  {
    name: "Swim Pace Calculator",
    href: "/health/swim-pace-calculator",
    description: "Determine your swimming pace per 100m or 100 yards.",
    category: "Health",
    icon: "H-SWIM",
  },
  {
    name: "Cycling Power to Weight Ratio",
    href: "/health/cycling-power-calculator",
    description: "Calculate your Watts per Kilogram (W/kg) to measure cycling performance.",
    category: "Health",
    icon: "H-WKG",
  },
  {
    name: "Marathon Finish Time Predictor",
    href: "/health/marathon-predictor-calculator",
    description: "Predict your marathon finish time based on your current performance.",
    category: "Health",
    icon: "H-42K",
  },
  {
    name: "Calories Burned Calculator",
    href: "/health/calories-burned-calculator",
    description: "Estimate calories burned during various physical activities and exercises.",
    category: "Health",
    icon: "H-KCAL",
  },
  {
    name: "Race Age Grading Calculator",
    href: "/health/age-grading-calculator",
    description: "Compare your race times across different ages and genders.",
    category: "Health",
    icon: "H-AGE",
  },
  {
    name: "Handicap Calculator (Golf)",
    href: "/health/golf-handicap-calculator",
    description: "Estimate your golf handicap index based on your recent scores.",
    category: "Health",
    icon: "H-GOLF",
  },
  ...PDF_TOOL_REGISTRY,
  ...IMAGE_TOOL_REGISTRY,
  ...TAILWIND_TOOL_REGISTRY,
  ...EXACT_TOOL_REGISTRY,
];

export function getRelatedFreeTools(currentHref: string, limit = 6) {
  const current = FREE_TOOLS.find((t) => t.href === currentHref);
  const sameCategory = FREE_TOOLS.filter(
    (t) => t.href !== currentHref && t.category === current?.category,
  );
  if (sameCategory.length >= limit) return sameCategory.slice(0, limit);
  // Top up with tools from other categories if same-category pool is small
  const others = FREE_TOOLS.filter(
    (t) => t.href !== currentHref && t.category !== current?.category,
  );
  return [...sameCategory, ...others].slice(0, limit);
}
