import type { FreeToolMeta } from "@/types/tools";
import { EXACT_TOOL_REGISTRY } from "@/lib/tools/exact-catalog";
import { IMAGE_TOOL_REGISTRY } from "@/lib/tools/image-catalog";
import { PDF_TOOL_REGISTRY } from "@/lib/tools/pdf-catalog";
import { TAILWIND_TOOL_REGISTRY } from "@/lib/tools/tailwind-catalog";

export const FREE_TOOL_CATEGORY_ROUTES: Record<FreeToolMeta["category"], string> = {
  AI: "/ai",
  Converter: "/converter",
  Finance: "/finance",
  Image: "/image",
  PDF: "/pdf",
  "Real Estate": "/real-estate",
  Tailwind: "/tailwind",
  Text: "/text",
  Utility: "/utility",
};

export const FREE_TOOLS: FreeToolMeta[] = [
  {
    name: "AI Humanizer",
    href: "/ai/ai-humanizer",
    description: "Rewrite AI-generated text to sound natural and human, with a short queue flow and no sign-up.",
    category: "AI",
    icon: "HUMN",
  },
  {
    name: "Salary Calculator",
    href: "/finance/salary-calculator",
    description: "Estimate salary after tax, take-home pay, and employer cost across major countries.",
    category: "Finance",
    icon: "PAY",
  },
  {
    name: "UAE Salary Calculator",
    href: "/finance/uae-salary-calculator",
    description: "Calculate monthly UAE net salary from basic salary, allowances, overtime, and deductions.",
    category: "Finance",
    icon: "AED",
  },
  {
    name: "UAE Gratuity Calculator",
    href: "/finance/uae-gratuity-calculator",
    description: "Estimate UAE end-of-service gratuity from monthly basic salary, contract dates, and unpaid leave.",
    category: "Finance",
    icon: "EOS",
  },
  {
    name: "UAE Visa Cost Calculator",
    href: "/finance/uae-visa-cost-calculator",
    description: "Estimate total UAE visa fees including government charges, medical, Emirates ID, and typing centre costs.",
    category: "Finance",
    icon: "VISA",
  },
  {
    name: "Mortgage Calculator",
    href: "/finance/mortgage-calculator",
    description: "Calculate monthly home loan payments with down payment, property tax, and insurance.",
    category: "Finance",
    icon: "MTG",
  },
  {
    name: "DTI Calculator",
    href: "/finance/dti-calculator",
    description: "Calculate debt-to-income ratio from gross monthly income and recurring monthly debt payments using the CFPB definition.",
    category: "Finance",
    icon: "DTI",
  },
  {
    name: "EMI Calculator",
    href: "/finance/emi-calculator",
    description: "Calculate monthly loan instalments for home, car, and personal loans.",
    category: "Finance",
    icon: "EMI",
  },
  {
    name: "Car Loan Calculator",
    href: "/finance/car-loan-calculator",
    description: "Calculate monthly payments for new and used car loans with down payment and trade-in value.",
    category: "Finance",
    icon: "AUTO",
  },
  {
    name: "Credit Card Payoff Calculator",
    href: "/finance/credit-card-payoff-calculator",
    description: "Estimate payoff time, total interest, and the payment needed to clear a credit card balance in 36 months.",
    category: "Finance",
    icon: "CARD",
  },
  {
    name: "Discount Calculator",
    href: "/finance/discount-calculator",
    description: "Calculate final price after discount or reverse-calculate the percent off from original and sale price.",
    category: "Finance",
    icon: "SALE",
  },
  {
    name: "VAT Calculator",
    href: "/finance/vat-calculator",
    description: "Add VAT to a net price or remove VAT from a gross price with country presets and custom rates.",
    category: "Finance",
    icon: "VAT",
  },
  {
    name: "GST Calculator",
    href: "/finance/gst-calculator",
    description: "Calculate Singapore GST using the current 9% standard rate and the official IRAS distinction between standard-rated, zero-rated, and exempt supplies.",
    category: "Finance",
    icon: "GST",
  },
  {
    name: "Profit Margin Calculator",
    href: "/finance/profit-margin-calculator",
    description: "Calculate margin, markup, gross profit, and selling price from cost in one pricing calculator.",
    category: "Finance",
    icon: "MRG",
  },
  {
    name: "Compound Interest Calculator",
    href: "/finance/compound-interest-calculator",
    description: "Project future value, contributions, and compound growth with optional inflation adjustment.",
    category: "Finance",
    icon: "CAGR",
  },
  {
    name: "Savings Goal Calculator",
    href: "/finance/savings-goal-calculator",
    description: "Calculate the monthly contribution needed to reach a savings target from your current balance, time horizon, and return assumption.",
    category: "Finance",
    icon: "SAVE",
  },
  {
    name: "Percentage Calculator",
    href: "/finance/percentage-calculator",
    description: "Instantly calculate percentages, percentage changes, and value proportions without formulas.",
    category: "Finance",
    icon: "PCT",
  },
  {
    name: "Click-Through Rate Calculator",
    href: "/finance/click-through-rate-calculator",
    description: "Calculate CTR from clicks and impressions, and estimate the clicks needed to hit a target click-through rate.",
    category: "Finance",
    icon: "CTR",
  },
  {
    name: "CPC / CPM Calculator",
    href: "/finance/cpc-cpm-calculator",
    description: "Calculate cost per click, cost per 1,000 impressions, and the spend needed to reach target traffic or reach goals.",
    category: "Finance",
    icon: "CPC",
  },
  {
    name: "ROI Calculator",
    href: "/finance/roi-calculator",
    description: "Calculate return on investment, net profit, cost basis, and annualized return from money in and money out.",
    category: "Finance",
    icon: "ROI",
  },
  {
    name: "Salary to Hourly Calculator",
    href: "/finance/salary-to-hourly-calculator",
    description: "Convert your annual salary to an hourly wage, daily rate, and monthly pay breakdown.",
    category: "Finance",
    icon: "PAY",
  },
  {
    name: "Rental Yield Calculator",
    href: "/real-estate/rental-yield-calculator",
    description: "Calculate gross yield, net yield, and net operating income from property price, rent, and annual costs.",
    category: "Real Estate",
    icon: "YLD",
  },
  {
    name: "Cap Rate Calculator",
    href: "/real-estate/cap-rate-calculator",
    description: "Calculate cap rate and NOI from property value, rent, and annual operating expenses.",
    category: "Real Estate",
    icon: "CAP",
  },
  {
    name: "Rent Affordability Calculator",
    href: "/real-estate/rent-affordability-calculator",
    description: "Estimate a monthly rent budget from income, debts, utilities, and target housing ratio.",
    category: "Real Estate",
    icon: "RENT",
  },
  {
    name: "Closing Costs Calculator",
    href: "/real-estate/closing-costs-calculator",
    description: "Estimate closing costs and total cash needed from purchase price, down payment, and fees.",
    category: "Real Estate",
    icon: "CLS",
  },
  {
    name: "Price per Square Foot Calculator",
    href: "/real-estate/price-per-square-foot-calculator",
    description: "Calculate price per square foot or square metre from total price and property area.",
    category: "Real Estate",
    icon: "PSF",
  },
  {
    name: "Rent vs Buy Calculator",
    href: "/real-estate/rent-vs-buy-calculator",
    description: "Compare renting and buying costs across the years you expect to stay in the property.",
    category: "Real Estate",
    icon: "BUY",
  },
  {
    name: "BMI Calculator",
    href: "/utility/bmi-calculator",
    description: "Calculate Body Mass Index (BMI) and find your ideal weight range using metric or imperial units.",
    category: "Utility",
    icon: "BMI",
  },
  {
    name: "Age Calculator",
    href: "/utility/age-calculator",
    description: "Calculate exact age in years, months, days, weeks, and total days from a birth date to any target date.",
    category: "Utility",
    icon: "AGE",
  },
  {
    name: "Tip Calculator",
    href: "/utility/tip-calculator",
    description: "Calculate gratuity, full bill total, and the per-person share from a bill amount and tip percentage.",
    category: "Utility",
    icon: "TIP",
  },
  {
    name: "UTM Link Builder",
    href: "/utility/utm-link-builder",
    description: "Build trackable campaign URLs with custom UTM parameters for Google Analytics.",
    category: "Utility",
    icon: "LINK",
  },
  {
    name: "QR Code Generator",
    href: "/utility/qr-code-generator",
    description: "Create and download static QR codes with custom colors and zero expiry limits.",
    category: "Utility",
    icon: "QR",
  },
  {
    name: "Barcode Generator",
    href: "/utility/barcode-generator",
    description: "Instantly create CODE128, UPC, and EAN barcodes and download high-quality PNGs.",
    category: "Utility",
    icon: "CODE",
  },
  {
    name: "QR Code Scanner",
    href: "/utility/qr-code-scanner",
    description: "Scan QR codes using your device camera or upload an image to decode web links instantly.",
    category: "Utility",
    icon: "CAM",
  },
  {
    name: "Barcode Scanner",
    href: "/utility/barcode-scanner",
    description: "Use your webcam or phone to scan 1D retail product barcodes and look them up online.",
    category: "Utility",
    icon: "SCAN",
  },
  {
    name: "Pomodoro Timer",
    href: "/utility/pomodoro-timer",
    description: "Boost productivity with a clean focus timer featuring 25-minute sprints and audio alarms.",
    category: "Utility",
    icon: "TIME",
  },
  {
    name: "Voice Dictation",
    href: "/text/voice-dictation",
    description: "Convert your voice into text in real-time using your browser's microphone natively.",
    category: "Text",
    icon: "MIC",
  },
  {
    name: "Meta Tags Generator",
    href: "/utility/meta-tags-generator",
    description: "Preview and generate SEO HTML Meta Tags and social media Open Graph cards.",
    category: "Utility",
    icon: "META",
  },
  {
    name: "Down Payment Calculator",
    href: "/real-estate/down-payment-calculator",
    description: "Work out the down payment amount, loan amount, and loan-to-value ratio from a home price and deposit percentage.",
    category: "Real Estate",
    icon: "DWN",
  },
  {
    name: "Mortgage Refinance Calculator",
    href: "/real-estate/mortgage-refinance-calculator",
    description: "Compare current and refinanced mortgage payments, break-even timing, and total remaining cost.",
    category: "Real Estate",
    icon: "REFI",
  },
  {
    name: "Rental Cash Flow Calculator",
    href: "/real-estate/rental-cash-flow-calculator",
    description: "Estimate monthly and annual rental cash flow after vacancy, mortgage costs, and operating expenses.",
    category: "Real Estate",
    icon: "FLOW",
  },
  {
    name: "Home Buying Budget Calculator",
    href: "/real-estate/home-buying-budget-calculator",
    description: "Estimate a realistic home budget from income, debt, down payment, ownership costs, and mortgage assumptions.",
    category: "Real Estate",
    icon: "BUD",
  },
  {
    name: "Lease Escalation Calculator",
    href: "/real-estate/lease-escalation-calculator",
    description: "Project rent increases across a lease term from the starting rent, annual escalation rate, and number of years.",
    category: "Real Estate",
    icon: "ESC",
  },
  {
    name: "Security Deposit Calculator",
    href: "/real-estate/security-deposit-calculator",
    description: "Estimate deposit amount and move-in cash from monthly rent, advance rent, and admin fees.",
    category: "Real Estate",
    icon: "DEP",
  },
  {
    name: "Property Management Fee Calculator",
    href: "/real-estate/property-management-fee-calculator",
    description: "Estimate management fees, leasing fees, and owner net income from a rental property's annual rent.",
    category: "Real Estate",
    icon: "PMF",
  },
  {
    name: "Stamp Duty Calculator",
    href: "/real-estate/stamp-duty-calculator",
    description: "Estimate stamp duty, legal costs, and registration fees from a property purchase price and duty rate.",
    category: "Real Estate",
    icon: "DUTY",
  },
  {
    name: "UK Stamp Duty Calculator",
    href: "/real-estate/uk-stamp-duty-calculator",
    description: "Calculate England and Northern Ireland SDLT with current residential bands, first-time relief, and surcharge options.",
    category: "Real Estate",
    icon: "UKSD",
  },
  {
    name: "Singapore Property Stamp Duty Calculator",
    href: "/real-estate/singapore-property-stamp-duty-calculator",
    description: "Calculate Singapore BSD, ABSD, and SSD using current buyer profiles and seller-duty regimes.",
    category: "Real Estate",
    icon: "SGSD",
  },
  {
    name: "Singapore Buyer's Stamp Duty Calculator",
    href: "/real-estate/singapore-buyers-stamp-duty-calculator",
    description: "Calculate Singapore BSD and ABSD using the current residential buyer profile rates.",
    category: "Real Estate",
    icon: "SGB",
  },
  {
    name: "Singapore Seller's Stamp Duty Calculator",
    href: "/real-estate/singapore-sellers-stamp-duty-calculator",
    description: "Estimate Singapore SSD from the acquisition date, disposal date, and current residential seller-duty rules.",
    category: "Real Estate",
    icon: "SGS",
  },
  {
    name: "NYC Transfer Tax Calculator",
    href: "/real-estate/nyc-transfer-tax-calculator",
    description: "Estimate New York City real property transfer tax from the transfer price and property type.",
    category: "Real Estate",
    icon: "NYC",
  },
  {
    name: "Dubai Property Transfer Fee Calculator",
    href: "/real-estate/dubai-property-transfer-fee-calculator",
    description: "Estimate Dubai Land Department transfer fees, trustee fees, and title-related charges from the sale price.",
    category: "Real Estate",
    icon: "DXB",
  },
  {
    name: "Scotland LBTT Calculator",
    href: "/real-estate/scotland-lbtt-calculator",
    description: "Calculate Scottish residential LBTT with first-time buyer relief and the Additional Dwelling Supplement.",
    category: "Real Estate",
    icon: "SCT",
  },
  {
    name: "Wales LTT Calculator",
    href: "/real-estate/wales-ltt-calculator",
    description: "Calculate Welsh residential Land Transaction Tax using the standard or higher residential rates.",
    category: "Real Estate",
    icon: "WLS",
  },
  {
    name: "Hong Kong Stamp Duty Calculator",
    href: "/real-estate/hong-kong-stamp-duty-calculator",
    description: "Estimate Hong Kong residential ad valorem stamp duty using the current Scale 2 rate schedule.",
    category: "Real Estate",
    icon: "HKG",
  },
  {
    name: "Dubai Mortgage Registration Calculator",
    href: "/real-estate/dubai-mortgage-registration-calculator",
    description: "Estimate Dubai mortgage registration fees from the mortgage amount using the published DLD fee structure.",
    category: "Real Estate",
    icon: "DMR",
  },
  {
    name: "Dubai Service Charge Calculator",
    href: "/real-estate/dubai-service-charge-calculator",
    description: "Estimate Dubai annual service charges from the title deed area and the approved DLD service charge rate per square foot.",
    category: "Real Estate",
    icon: "DSC",
  },
  {
    name: "Word Frequency Counter",
    href: "/text/word-frequency",
    description: "Analyze repeated words, filter stop words, and surface the most-used terms in any text block.",
    category: "Text",
    icon: "WORD",
  },
  {
    name: "Character Counter",
    href: "/text/character-counter",
    description: "Count characters, no-space characters, words, sentences, paragraphs, and reading time instantly.",
    category: "Text",
    icon: "CHAR",
  },
  {
    name: "Case Converter",
    href: "/text/case-converter",
    description: "Convert text into uppercase, lowercase, title case, sentence case, camelCase, PascalCase, kebab-case, and snake_case.",
    category: "Text",
    icon: "CASE",
  },
  {
    name: "Duplicate Word Finder",
    href: "/text/duplicate-word-finder",
    description: "Find repeated words, duplicate counts, and overused terms quickly in any text block.",
    category: "Text",
    icon: "DUP",
  },
  {
    name: "Em Dash Remover",
    href: "/text/em-dash-remover",
    description: "Replace em dashes and en dashes with a comma, hyphen, space, or nothing in one pass.",
    category: "Text",
    icon: "DASH",
  },
  {
    name: "Strikethrough Text",
    href: "/text/strikethrough-text",
    description: "Generate strike-through, underline, double underline, dotted, and wave-style Unicode text effects.",
    category: "Text",
    icon: "LINE",
  },
  {
    name: "Reverse Text Generator",
    href: "/text/reverse-text-generator",
    description: "Reverse full text, reverse word order, or reverse each word instantly in one text utility.",
    category: "Text",
    icon: "REV",
  },
  {
    name: "Morse Code Translator",
    href: "/text/morse-code-translator",
    description: "Translate text to Morse code and Morse code back to text with support for letters, numbers, and punctuation.",
    category: "Text",
    icon: "MORSE",
  },
  {
    name: "Binary Code Translator",
    href: "/text/binary-code-translator",
    description: "Translate text to binary and binary back to text with 8-bit byte conversion and validation.",
    category: "Text",
    icon: "BIN",
  },
  {
    name: "ASCII Art Generator",
    href: "/text/ascii-art-generator",
    description: "Generate FIGlet-style ASCII art banners with a curated font set and layout controls.",
    category: "Text",
    icon: "ASCII",
  },
  {
    name: "Image to Text OCR",
    href: "/text/convert-image-to-text",
    description: "Convert image to text online with OCR, progress feedback, and copy-ready output.",
    category: "Text",
    icon: "OCR",
  },
  {
    name: "Word Cloud Generator",
    href: "/text/word-cloud-generator",
    description: "Generate a word cloud from text with frequency sizing, filters, and copyable top-word output.",
    category: "Text",
    icon: "CLOUD",
  },
  {
    name: "Remove Duplicate Lines",
    href: "/text/remove-duplicate-lines",
    description: "Remove repeated lines from multiline text while keeping the first occurrence of each line.",
    category: "Text",
    icon: "LINES",
  },
  ...PDF_TOOL_REGISTRY,
  ...IMAGE_TOOL_REGISTRY,
  ...TAILWIND_TOOL_REGISTRY,
  ...EXACT_TOOL_REGISTRY,
];

export function getRelatedFreeTools(currentHref: string, limit = 6) {
  const current = FREE_TOOLS.find((t) => t.href === currentHref);
  const sameCategory = FREE_TOOLS.filter(
    (t) => t.href !== currentHref && t.category === current?.category,
  );
  if (sameCategory.length >= limit) return sameCategory.slice(0, limit);
  // Top up with tools from other categories if same-category pool is small
  const others = FREE_TOOLS.filter(
    (t) => t.href !== currentHref && t.category !== current?.category,
  );
  return [...sameCategory, ...others].slice(0, limit);
}
