import { BackgroundPreset } from "./types";

export const backgroundPresets: BackgroundPreset[] = [
    {
        id: "arrows",
        name: "Pointed Arrows",
        type: "continuous",
        pattern: "arrows",
        opacity: 0.12,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "round-arrows",
        name: "Rounded Arrows",
        type: "continuous",
        pattern: "round-arrows",
        opacity: 0.12,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "waves",
        name: "Wobbly Waves",
        type: "continuous",
        pattern: "waves",
        opacity: 0.1,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "grid",
        name: "Grid",
        type: "continuous",
        pattern: "grid",
        opacity: 0.08,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "dots",
        name: "Soft Dots",
        type: "continuous",
        pattern: "dots",
        opacity: 0.08,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "topographic",
        name: "Topographic Lines",
        type: "continuous",
        pattern: "topographic",
        opacity: 0.08,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "chevron",
        name: "Chevron Flow",
        type: "continuous",
        pattern: "chevron",
        opacity: 0.08,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "paper",
        name: "Paper Texture",
        type: "continuous",
        pattern: "paper",
        opacity: 0.12,
        scale: 1,
        colorMode: "soft",
    },
    {
        id: "glow",
        name: "Glow Aura",
        type: "continuous",
        pattern: "glow",
        opacity: 0.14,
        scale: 1.1,
        colorMode: "accent",
    },
    {
        id: "diagonal-lines",
        name: "Diagonal Lines",
        type: "continuous",
        pattern: "diagonal-lines",
        opacity: 0.08,
        scale: 1,
        colorMode: "soft",
    },
];

export const getBackgroundPresetById = (id: string) =>
    backgroundPresets.find((bg) => bg.id === id);